using System;

namespace Backend_SEP490.DTOs.Request;

public class VoucherIssueRequest
{
    public string? OwnerUserId { get; set; }
    public string DiscountType { get; set; } = "Fixed";
    public decimal DiscountValue { get; set; }
    public decimal? MinOrderAmount { get; set; }
    public decimal? MaxDiscountAmount { get; set; }
    public DateTime StartDateUtc { get; set; } = DateTime.UtcNow;
    public DateTime EndDateUtc { get; set; } = DateTime.UtcNow.AddMonths(1);
    public int? UsageLimit { get; set; } = 1;
    public bool IsShared { get; set; }
    public bool SingleUse { get; set; } = true;
    public bool IsAutoGenerated { get; set; }
    public string? Source { get; set; }
    public string? Description { get; set; }
    public string? CreatorUserId { get; set; }
    public string? NotificationMessage { get; set; }
    public string? CodePrefix { get; set; }
}
