@echo off
echo 🧪 Running tests...
dotnet test --logger "trx;LogFileName=test-results.trx"
echo 📊 Generating HTML report...
reportgenerator -reports:Backend_SEP490.IntegrationTests\TestResults\TestResults.trx -targetdir:TestReport
echo ✅ Done! Opening report...
start TestReport\index.html
