import React, {
  createContext,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react';
import PropTypes from 'prop-types';

const translations = {
  vi: {
    nav: {
      home: 'Trang chủ',
      about: 'Về chúng tôi',
      shop: 'Mua sắm',
      blog: 'Bài viết',
      contact: 'Liên hệ',
      policy: 'Chính sách',
    },
    footer: {
      contactTitle: 'Liên hệ',
      address: 'Hòa Lạc, Thạch Thất, Hà Nội',
      email: 'Hoalachandicraft@gmail.com',
      phone: '0921643475',
      store: {
        title: 'Cửa hàng',
        dragonfly: 'Chuồn chuồn tre Thạch Xá',
        fan: 'Quạt Quảng Sơn',
        bamboo: 'Mây tre đan',
        allProducts: 'Xem tất cả sản phẩm',
      },
      policy: {
        title: 'Chính sách',
      },
      explore: {
        title: 'Khám phá',
        blog: 'Tin tức làng nghề',
        collections: 'Bộ sưu tập sản phẩm',
      },
      copyright: 'Copyright © 2025 Hoalachandicraft · All Rights Reserved',
    },
    header: {
      searchPlaceholder: 'Tìm kiếm...',
      login: 'Đăng nhập',
      profile: 'Tài khoản của tôi',
      orders: 'Đơn hàng',
      logout: 'Đăng xuất',
      notificationsEmpty: 'Không có thông báo mới.',
      cartTooltip: 'Giỏ hàng',
      artisanDashboard: 'Quản lý cửa hàng',
    },
    pageTitles: {
      brand: 'Hoa Lạc Handicraft',
      home: 'Trang chủ',
      about: 'Về chúng tôi',
      shop: 'Cửa hàng',
      blog: 'Bài viết',
      blogDetail: 'Chi tiết bài viết',
      contact: 'Liên hệ',
      policy: 'Chính sách',
      cart: 'Giỏ hàng',
      checkout: 'Thanh toán',
      orderHistory: 'Lịch sử đơn hàng',
      orderTracking: 'Theo dõi đơn hàng',
      orderSuccess: 'Đặt hàng thành công',
      paymentResult: 'Kết quả thanh toán',
      profile: 'Tài khoản của tôi',
      login: 'Đăng nhập',
      register: 'Đăng ký',
      forgotPassword: 'Quên mật khẩu',
      productDetail: 'Chi tiết sản phẩm',
      collectionDetail: 'Bộ sưu tập',
      artisanShop: 'Gian hàng nghệ nhân',
      artisanDashboard: 'Quản lý gian hàng',
      adminDashboard: 'Bảng điều khiển Admin',
      storytellingDetail: 'Câu chuyện làng nghề',
      notFound: 'Không tìm thấy trang',
    },
    profile: {
      common: {
        sending: 'Đang gửi...',
        processing: 'Đang xử lý...',
        saving: 'Đang lưu...',
        cancel: 'Hủy',
      },
      changePassword: {
        title: 'Đổi mật khẩu',
        emailLabel: 'Email',
        sendOtp: 'Gửi OTP',
        otpLabel: 'OTP',
        otpPlaceholder: 'Nhập mã OTP',
        otpRequired: 'Vui lòng nhập mã OTP.',
        passwordRequired: 'Vui lòng điền đầy đủ mật khẩu.',
        passwordMismatch: 'Mật khẩu xác nhận không khớp.',
        passwordRule: 'Mật khẩu phải có ≥ 6 ký tự, ít nhất 1 chữ viết hoa và 1 ký tự đặc biệt.',
        newPasswordLabel: 'Mật khẩu mới',
        newPasswordPlaceholder: 'Nhập mật khẩu mới',
        confirmPasswordLabel: 'Xác nhận mật khẩu',
        confirmPasswordPlaceholder: 'Nhập lại mật khẩu',
        otpSent: 'OTP đã được gửi tới email của bạn.',
        emailNotFound: 'Email không tồn tại trong hệ thống.',
        resetSuccess: 'Mật khẩu đã được thay đổi thành công.',
        otpInvalid: 'Mã OTP không hợp lệ hoặc đã hết hạn.',
        submit: 'Đổi mật khẩu',
      },
      errors: {
        fetchUser: 'Không thể lấy thông tin người dùng.',
      },
      avatar: {
        sizeError: 'Kích thước ảnh không được vượt quá 5MB.',
        typeError: 'Vui lòng chọn file ảnh.',
        updateSuccess: 'Cập nhật ảnh đại diện thành công!',
        updateError: 'Không thể cập nhật ảnh đại diện.',
        view: 'Xem ảnh',
        change: 'Đổi ảnh',
      },
      info: {
        title: 'Thông tin tài khoản',
        nameLabel: 'Tên',
        phoneLabel: 'Số điện thoại',
        emailLabel: 'Email',
        usernameLabel: 'Tên đăng nhập',
        dobLabel: 'Ngày tháng năm sinh',
        dobPlaceholder: 'dd/mm/yyyy',
        dobDayPlaceholder: 'dd',
        dobMonthPlaceholder: 'mm',
        dobYearPlaceholder: 'yyyy',
        dobInvalid: 'Ngày sinh không hợp lệ.',
        dobAgeLimit: 'Ngày sinh vượt quá giới hạn tuổi cho phép.',
        updateSuccess: 'Cập nhật thông tin thành công!',
        updateError: 'Không thể cập nhật thông tin.',
        editButton: 'Sửa thông tin',
        saveButton: 'Lưu thông tin',
      },
      address: {
        title: 'Địa chỉ giao hàng',
        addButton: 'Thêm địa chỉ',
        closeButton: 'Đóng',
        empty: 'Chưa có địa chỉ nào',
        detailFallback: 'Chưa có địa chỉ chi tiết',
        defaultBadge: 'Mặc định',
        editButton: 'Xem / Sửa',
        deleteButton: 'Xóa',
        singleDefaultNotice: 'Bạn chỉ có một địa chỉ, địa chỉ này sẽ được đặt làm mặc định.',
        validation: {
          missingFields: 'Vui lòng chọn đầy đủ tỉnh, quận, phường và nhập địa chỉ chi tiết.',
          invalidProvinceDistrict: 'Mã tỉnh hoặc quận không hợp lệ.',
        },
        updateSuccess: 'Cập nhật địa chỉ thành công!',
        createSuccess: 'Thêm địa chỉ thành công!',
        saveError: 'Không thể lưu địa chỉ.',
        deleteSuccess: 'Xóa địa chỉ thành công.',
        deleteError: 'Không thể xóa địa chỉ.',
        loadProvincesError: 'Không thể tải danh sách tỉnh/thành.',
        loadDistrictsError: 'Không thể tải danh sách quận/huyện.',
        loadWardsError: 'Không thể tải danh sách phường/xã.',
        form: {
          recipientLabel: 'Họ tên người nhận',
          phoneLabel: 'Số điện thoại',
          provinceLabel: 'Tỉnh/Thành phố',
          provinceLoading: 'Đang tải tỉnh/thành phố...',
          provincePlaceholder: 'Chọn tỉnh/thành phố',
          districtLabel: 'Quận/Huyện',
          districtSelectProvince: 'Vui lòng chọn tỉnh/thành phố trước',
          districtLoading: 'Đang tải quận/huyện...',
          districtPlaceholder: 'Chọn quận/huyện',
          wardLabel: 'Phường/Xã',
          wardSelectDistrict: 'Vui lòng chọn quận/huyện trước',
          wardLoading: 'Đang tải phường/xã...',
          wardPlaceholder: 'Chọn phường/xã',
          detailLabel: 'Địa chỉ chi tiết',
          detail2Label: 'Địa chỉ chi tiết 2 (nếu có)',
          defaultCheckbox: 'Đặt làm địa chỉ mặc định',
          saving: 'Đang lưu...',
          saveButton: 'Lưu địa chỉ',
        },
        deleteModal: {
          title: 'Xóa địa chỉ',
          message: 'Bạn có chắc muốn xóa địa chỉ này? Hành động này không thể hoàn tác.',
          cancel: 'Hủy',
          confirm: 'Xóa',
        },
      },
      loading: {
        title: 'Đang tải thông tin...',
        subtitle: 'Vui lòng chờ trong giây lát',
      },
      sidebar: {
        accountInfo: 'Thông tin tài khoản',
        orderHistory: 'Lịch sử mua hàng',
        wishlist: 'Sản phẩm đã thích',
        artisanShop: 'Cửa hàng của tôi',
        artisanRegister: 'Đăng ký làm người bán hàng',
        changePassword: 'Đổi mật khẩu',
        logout: 'Đăng xuất',
      },
      artisanApplication: {
        status: {
          pending: {
            label: 'Chờ duyệt',
            description: 'Đơn đăng ký của bạn đang được đội ngũ quản trị xem xét. Vui lòng đợi thêm.',
          },
          approved: {
            label: 'Đã duyệt',
            description: 'Đơn đăng ký đã được chấp nhận. Bạn có thể bắt đầu quản lý cửa hàng của mình.',
          },
          rejected: {
            label: 'Đã từ chối',
            description: 'Đơn đăng ký đã bị từ chối. Vui lòng xem lý do và liên hệ hỗ trợ nếu cần.',
          },
          unknown: {
            label: 'Không xác định',
            description: '',
          },
        },
      },
    },
    home: {
      collections: {
        title: 'Bộ sưu tập sản phẩm',
        description: 'Khám phá những bộ sưu tập được tuyển chọn kỹ lưỡng, nơi mỗi thiết kế đều mang dấu ấn của làng nghề Hòa Lạc.',
        empty: 'Không có sản phẩm nào.',
        badge: 'Bộ sưu tập',
        cta: 'Khám phá ngay',
        error: 'Không thể tải bộ sưu tập.',
      },
      hero: {
        initialTitle: 'Nghệ thuật truyền thống Hòa Lạc',
        initialDescription: 'Nơi hội tụ tinh hoa của những đôi bàn tay tài hoa, nơi mỗi đường nét được tạo nên từ ký ức làng nghề và khát vọng đưa bản sắc Việt vươn xa. Chúng tôi trân trọng từng câu chuyện phía sau sản phẩm, để bạn cảm nhận rõ hơi thở truyền thống trong không gian hiện đại.',
        overlayTitle: 'Chào mừng đến với\nWebsite thủ công mỹ nghệ Hòa Lạc',
        cta: 'Khám phá',
        introTitle: 'Từng nhịp thở của làng nghề, từng câu chuyện của người nghệ nhân được dệt nên bằng sự nâng niu và lòng tự hào.',
        introDescription: 'Từ những ngày đầu đặt nền móng, người dân Hòa Lạc đã gìn giữ tinh thần sáng tạo, để mỗi sản phẩm không chỉ là vật dụng mà còn là ký ức của một vùng đất. Những đôi tay tài hoa đã truyền nhau kỹ thuật, hơi thở văn hóa và cả niềm tin rằng nghề truyền thống là sợi dây gắn kết quá khứ với hiện tại.',
        values: {
          heritage: {
            title: 'Nếp Nghề Truyền Lại',
            description: 'Qua từng thế hệ, những bí quyết chế tác được truyền dạy bên bếp lửa ấm. Họ kể cho nhau nghe về nhịp chày, về mùi hương tre phơi nắng và niềm tự hào khi sản phẩm hoàn thiện.',
          },
          culture: {
            title: 'Sắc Màu Văn Hóa',
            description: 'Mỗi họa tiết là một biểu tượng, kể về mùa vụ, tín ngưỡng, nếp sống. Người nghệ nhân chọn màu sắc theo cảm xúc, tạo nên những tác phẩm rực rỡ nhưng hài hòa như chính nhịp sống làng nghề.',
          },
          contemporary: {
            title: 'Hơi Thở Đương Đại',
            description: 'Khi thế giới đổi thay, Hòa Lạc vẫn giữ linh hồn truyền thống nhưng không ngừng cải tiến. Những thiết kế mới mang tính ứng dụng cao, đưa làng nghề tiến gần hơn tới cuộc sống hiện đại.',
          },
        },
        closing: 'Hành trình của chúng tôi là hành trình kể lại những câu chuyện chân thật nhất về con người Hòa Lạc – những người đã chọn gắn bó cả đời với nghề để bảo tồn bản sắc Việt.',
      },
      featured: {
        badge: 'Tinh hoa chọn lọc',
        title: 'Sản phẩm nổi bật',
        description: 'Những tác phẩm thủ công được yêu thích nhất, hội tụ sự tỉ mỉ của người nghệ nhân Hòa Lạc và chất liệu truyền thống.',
        cta: 'Xem cửa hàng',
      },
      contactSection: {
        badge: 'Kết nối với Hòa Lạc',
        title: 'Liên hệ để chạm vào tinh hoa nghề Việt',
        description: 'Chúng tôi luôn sẵn sàng đồng hành cùng bạn trong hành trình khám phá và gìn giữ giá trị thủ công truyền thống.',
        namePlaceholder: 'Họ và tên',
        emailPlaceholder: 'Email',
        phonePlaceholder: 'Số điện thoại',
        messagePlaceholder: 'Viết đôi lời cùng chúng tôi',
        cta: 'Liên hệ ngay',
        note: 'Hoặc quý khách có thể kết nối trực tiếp qua các kênh dưới đây',
        hotlineLabel: 'Hotline',
      },
      artisanCraft: {
        badge: 'Hành trình làng nghề',
        title: 'Không gian nghệ nhân Hòa Lạc',
        description: 'Dõi theo nhịp sống của những nghệ nhân, nơi từng đường khắc và nét vẽ đều được nâng niu để giữ trọn tinh hoa truyền thống.',
        slides: {
          first: {
            title: 'Khám phá làng nghề',
            subtitle: 'Tinh hoa thủ công Việt',
            content: 'Mỗi sản phẩm là câu chuyện về bàn tay nghệ nhân, về những giá trị truyền thống được gìn giữ và sáng tạo.',
          },
          second: {
            title: 'Kết nối thợ thủ công',
            subtitle: 'Từ bàn tay đến trái tim',
            content: 'Gặp gỡ những người thợ tài hoa, mang sản phẩm thủ công đến gần hơn với cuộc sống hiện đại.',
          },
          third: {
            title: 'Bảo tồn và phát triển',
            subtitle: 'Di sản sống động',
            content: 'Cùng tiếp sức để làng nghề phát triển bền vững, đưa sản phẩm thủ công Việt vươn xa thế giới.',
          },
        },
        sliderTag: 'Truyền thống & Hiện đại',
      },
      discover: {
        badge: 'Góc truyện làng nghề',
        title: 'Khám phá Hòa Lạc',
        description: 'Những câu chuyện, sự kiện và cảm hứng xoay quanh hành trình gìn giữ và phát triển nghề thủ công truyền thống.',
        cta: 'Xem tất cả bài viết',
        cardTag: 'Khám phá',
      },
    },
    about: {
      breadcrumbHome: 'Trang chủ',
      breadcrumbCurrent: 'Về chúng tôi',
      cloudIntro: {
        description: 'Hòa Lạc – không chỉ là một địa danh, mà còn là nơi hội tụ tinh hoa của những đôi bàn tay tài hoa, nơi mỗi thớ gỗ, sợi tre, hay mảnh gốm đều được thổi hồn, mang theo câu chuyện của người nghệ nhân và văn hóa truyền thống.',
      },
      mission: {
        title: 'Sứ mệnh của chúng tôi',
        items: {
          first: 'Gìn giữ tinh hoa làng nghề Hòa Lạc',
          second: 'Kết nối nghệ nhân với cộng đồng yêu thủ công',
          third: 'Lan tỏa vẻ đẹp văn hóa Việt qua từng sản phẩm',
        },
      },
      whyUs: {
        titleLine1: 'Vì sao lại chọn',
        titleLine2: 'Hoa Lac Handicraft?',
        reasons: {
          first: 'Chân thật & thủ công: Mỗi sản phẩm đều được làm bằng tay, tỉ mỉ trong từng chi tiết, mang hồn cốt của người thợ Việt.',
          second: 'Gắn kết truyền thống & hiện đại: Chúng tôi giữ nguyên nét xưa, nhưng thể hiện theo phong cách gần gũi, phù hợp với đời sống hôm nay.',
          third: 'Sản phẩm mang câu chuyện: Mỗi món đồ không chỉ đẹp mà còn kể về một làng nghề, một con người, một niềm tự hào văn hóa.',
          fourth: 'Bền vững & ý nghĩa: Chúng tôi hướng đến phát triển bền vững, đồng hành cùng nghệ nhân và lan tỏa giá trị thủ công tới cộng đồng.',
        },
      },
    },
    shop: {
      loading: 'Đang tải sản phẩm...',
      empty: 'Không có sản phẩm nào.',
      banner: {
        title: 'Chào mừng đến với website thủ công mỹ nghệ Hòa Lạc',
        subtitle: 'Nơi quy tụ các tác phẩm thủ công tinh xảo',
        cta: 'Khám phá sản phẩm',
      },
      filter: {
        allProductsHeading: 'Tất cả sản phẩm',
        allLabel: 'Tất cả',
        unknownCategory: 'Không tên',
        searchPlaceholder: 'Tìm kiếm sản phẩm...',
        sortButton: 'Sắp xếp',
        sortTitle: 'Sắp xếp theo:',
        scrollLeft: 'Cuộn sang trái',
        scrollRight: 'Cuộn sang phải',
        sort: {
          default: 'Mặc định',
          lowToHigh: 'Giá: thấp đến cao',
          highToLow: 'Giá: cao đến thấp',
          aToZ: 'Tên A -> Z',
          zToA: 'Tên Z -> A',
        },
        searchButton: 'Tìm kiếm',
      },
    },
    blog: {
      breadcrumb: {
        home: 'Trang chủ',
        current: 'Bài viết',
      },
      hero: {
        badge: 'Tin tức làng nghề',
        emptyHighlights: 'Các bài viết sẽ được nổi bật trong thời gian tới.',
        emptyList: 'Chưa có bài viết nào được xuất bản. Vui lòng quay lại sau.',
      },
      featured: {
        badge: 'Bài viết nổi bật',
        title: 'Các bài viết gần đây',
        countLabel: 'Hiển thị {count} trên {total} bài viết',
        readMore: 'Đọc bài viết',
        empty: 'Các câu chuyện mới sẽ sớm được xuất bản.',
      },
      updating: 'Đang cập nhật',
      authorFallback: 'G90 Editorial',
      loadError: 'Không thể tải các bài viết.',
    },
    blogDetail: {
      missing: 'Bài viết không tồn tại.',
      loadError: 'Không thể tải bài viết.',
      backToBlog: 'Quay lại trang blog',
      byLabel: 'Bởi',
      postedIn: 'Đăng ở',
      mainContent: 'Nội dung chính',
      statusLabel: 'Tình trạng',
      idLabel: 'Mã bài viết',
      statusFallback: 'Active',
      categoryFallback: 'Tin tức',
      contentUpdating: 'Nội dung sẽ được cập nhật.',
      relatedBadge: 'Có thể bạn sẽ thích',
      relatedTitle: 'Bài viết liên quan',
      viewAll: 'Xem tất cả',
      relatedSummaryFallback: 'Khám phá thêm về câu chuyện thủ công truyền thống.',
    },
    productCard: {
      fallbackDescription: 'Sản phẩm thủ công mang đậm nét truyền thống',
      sold: '{count} lượt bán',
      rating: '({count})',
      priceLabel: 'Giá bán',
      stock: 'Còn {stock} sản phẩm',
      viewDetail: 'Xem chi tiết',
      addToCart: 'Giỏ hàng',
      buyNow: 'Mua ngay',
      priceSuffix: ' VND',
      soldOut: 'Hết hàng',
    },
    relation: {
      title: 'Sản phẩm tương tự',
      subtitle: 'Khám phá thêm các sản phẩm thủ công tinh xảo',
      loading: 'Đang tải sản phẩm liên quan...',
    },
    contact: {
      title: 'Liên hệ',
      description: 'Đừng ngại gửi cho chúng tôi thông điệp của bạn. Đội ngũ Hòa Lạc Handicraft luôn sẵn sàng lắng nghe.',
      form: {
        name: 'Họ và tên',
        email: 'Email',
        phone: 'Số điện thoại',
        message: 'Nội dung',
        submit: 'Gửi tin nhắn',
        sending: 'Đang gửi...',
        validation: {
          nameRequired: 'Vui lòng nhập họ và tên.',
          emailRequired: 'Vui lòng nhập email.',
          emailInvalid: 'Email không hợp lệ.',
          phoneRequired: 'Vui lòng nhập số điện thoại.',
          phoneInvalid: 'Số điện thoại không hợp lệ (9-11 chữ số).',
          messageRequired: 'Vui lòng nhập nội dung.',
          messageLength: 'Nội dung cần tối thiểu {min} ký tự.',
        },
      },
      infoTitle: 'Thông tin liên hệ',
      office: 'Văn phòng',
      address: 'Khu Công nghệ cao Hòa Lạc, Thạch Thất, Hà Nội',
      phone: 'Điện thoại',
      emailLabel: 'Email',
      hoursTitle: 'Giờ làm việc',
      hoursValue: 'Thứ 2 - Thứ 6: 8:30 - 17:30',
    },
    policy: {
      title: 'Chính sách',
      updated: 'Cập nhật lần cuối: Tháng 11/2025',
      privacyTitle: 'Chính sách bảo mật',
      privacyContent: 'Chúng tôi cam kết bảo vệ dữ liệu cá nhân của bạn và chỉ sử dụng để cung cấp dịch vụ. Mọi thông tin được mã hóa và lưu trữ an toàn.',
      shippingTitle: 'Chính sách vận chuyển',
      shippingContent: 'Đơn hàng được xử lý trong 24 giờ và giao trong 3-5 ngày làm việc. Chúng tôi hỗ trợ giao hàng toàn quốc qua các đối tác uy tín.',
      returnTitle: 'Chính sách đổi trả',
      returnContent: 'Bạn có thể đổi trả sản phẩm trong vòng 7 ngày kể từ khi nhận hàng nếu sản phẩm bị lỗi hoặc hư hỏng trong quá trình vận chuyển.',
    },
    cart: {
      title: 'Giỏ hàng của bạn',
      empty: 'Giỏ hàng của bạn đang trống.',
      headerProduct: 'Sản phẩm',
      headerQuantity: 'Số lượng',
      headerPrice: 'Giá',
      headerSubtotal: 'Thành tiền',
      summaryTitle: 'Thông tin đơn hàng',
      subtotal: 'Tạm tính',
      shipping: 'Phí vận chuyển',
      total: 'Tổng cộng',
      checkout: 'Tiến hành đặt hàng',
      continueShopping: 'Tiếp tục mua sắm',
      itemsCount: '{count} sản phẩm',
      updating: 'Đang cập nhật...',
      remove: 'Xóa',
      banner: {
        title: 'Giỏ hàng của bạn',
        description: 'Kiểm tra lại sản phẩm trước khi thanh toán để đảm bảo mọi thứ chính xác.',
      },
      emptyInfo: 'Giỏ hàng của bạn đang trống, thêm sản phẩm để tiếp tục nhé!',
      unavailableNotice: 'Sản phẩm đã hết hàng hoặc ngừng kinh doanh.',
      unavailableOnly: 'Giỏ hàng của bạn hiện chỉ chứa các sản phẩm đã hết hàng. Vui lòng xóa chúng trước khi tiếp tục.',
      unavailableConfirm: 'Một số sản phẩm trong giỏ hàng đã hết hàng. Tiếp tục thanh toán với các sản phẩm còn hàng chứ?',
      shopFallback: 'Cửa hàng',
      shopCodeLabel: 'Mã cửa hàng',
      visitShop: 'Xem cửa hàng',
      shopSubtotal: 'Tổng tiền đơn hàng',
      checkoutShop: 'Đặt hàng',
      checkoutShopDisabled: 'Các sản phẩm trong giỏ hàng này đã hết hàng.',
      checkoutContextLabel: 'Cửa hàng được chọn',
      selectAll: 'Chọn tất cả',
      selectedSummary: 'Đã chọn {count} sản phẩm - {amount}',
      emptySelection: 'Chọn sản phẩm để xem tổng tiền.',
      shopSelectLabel: 'Chọn cửa hàng này',
      itemSelectLabel: 'Chọn sản phẩm này',
      multipleShopsSelected: 'Đã chọn {count} cửa hàng',
      selectedCountLabel: 'Sản phẩm đã chọn',
      selectedAmountLabel: 'Tạm tính',
    },
    messages: {
      loginRequired: 'Vui lòng đăng nhập để tiếp tục.',
      loginToAddCart: 'Đăng nhập để thêm vào giỏ hàng.',
      loginToBuyNow: 'Đăng nhập để mua ngay.',
      addedToCart: 'Đã thêm sản phẩm vào giỏ hàng.',
      addedToCartRedirect: 'Đã thêm sản phẩm, đang chuyển tới giỏ hàng...',
      addToCartError: 'Không thể thêm sản phẩm vào giỏ hàng.',
      cartLoadError: 'Không thể tải giỏ hàng.',
      cartUpdateSuccess: 'Đã cập nhật số lượng.',
      cartUpdateError: 'Cập nhật số lượng thất bại.',
      cartRemoveSuccess: 'Đã xóa sản phẩm khỏi giỏ hàng.',
      cartRemoveError: 'Xóa sản phẩm thất bại.',
      checkoutComingSoon: 'Tính năng thanh toán đang được phát triển.',
      cartEmpty: 'Giỏ hàng của bạn đang trống.',
      addressRequired: 'Vui lòng chọn địa chỉ giao hàng.',
      orderSuccess: 'Đặt hàng thành công.',
      orderError: 'Không thể đặt hàng. Vui lòng thử lại.',
      wishlistAdded: 'Đã thêm vào yêu thích.',
      wishlistRemoved: 'Đã xóa khỏi yêu thích.',
      wishlistLoginRequired: 'Đăng nhập để quản lý danh sách yêu thích.',
      removedUnavailable: 'Một số sản phẩm đã hết hàng và được loại khỏi đơn thanh toán.',
      redirectVnpay: 'Đang chuyển hướng đến VNPAY...',
      voucherLoadError: 'Không thể tải danh sách voucher.',
      contactSuccess: 'Cảm ơn bạn! Chúng tôi sẽ phản hồi trong thời gian sớm nhất.',
      contactError: 'Không thể gửi thông tin liên hệ. Vui lòng thử lại sau.',
    },
    orderHistory: {
      page: {
        title: 'Lịch sử đơn hàng',
        breadcrumbHome: 'Trang chủ',
        breadcrumbCurrent: 'Lịch sử đơn hàng',
        stats: {
          totalSpentTitle: 'Tổng chi tiêu',
          totalSpentCaption: 'Dựa trên bộ lọc hiện tại',
          ordersShownTitle: 'Số đơn hiển thị',
          ordersShownCaption: 'Trong trang hiện tại',
        },
        filters: {
          title: 'Bộ lọc nâng cao',
          reset: 'Xóa bộ lọc',
          startDateLabel: 'Từ ngày',
          endDateLabel: 'Đến ngày',
          selectDay: 'Ngày',
          selectMonth: 'Tháng',
          selectYear: 'Năm',
          paymentMethodLabel: 'Phương thức thanh toán',
          paymentMethod: {
            all: 'Tất cả',
            COD: 'Thanh toán khi nhận hàng',
            VNPAY: 'VNPAY',
          },
        },
      },
      statuses: {
        all: 'Tất cả',
        WaitingForPickup: 'Chờ xác nhận',
        Shipping: 'Đang giao',
        Completed: 'Đã nhận hàng',
        Cancelled: 'Đã hủy',
        Paid: 'Đã thanh toán',
        paidWaitingConfirmation: 'Đã thanh toán chờ bên Cửa hàng xác nhận',
        paidConfirmedAwaitingShipping: 'Đơn hàng đã được xác nhận, Cửa hàng đang chuẩn bị gửi hàng cho bên vận chuyển',
        default: 'Không xác định',
      },
      loading: 'Đang tải...',
      pagination: {
        prev: 'Trước',
        next: 'Sau',
        label: 'Trang {current}/{total}',
      },
      empty: {
        title: 'Chưa có đơn hàng nào',
      },
      list: {
        orderLabel: 'Đơn hàng: {orderNumber}',
        paymentMethodLabel: 'Phương thức thanh toán',
        paymentMethodCOD: 'Thanh toán khi nhận hàng',
        paymentMethodVNPAY: 'VNPAY',
        totalLabel: 'Tổng tiền',
        viewShop: 'Xem cửa hàng',
        actions: {
          viewDetail: 'Xem chi tiết',
          requestReturn: 'Hoàn đơn',
          continuePayment: 'Tiếp tục thanh toán',
          confirmReceived: 'Đã nhận được hàng',
          confirming: 'Đang xác nhận...',
          cancelOrder: 'Hủy đơn',
        },
        toast: {
          continueProcessing: 'Đang xử lý thanh toán...',
          continueMissingUrl: 'Không thể lấy link thanh toán. Vui lòng thử lại.',
          continueError: 'Có lỗi xảy ra khi tiếp tục thanh toán. Vui lòng thử lại.',
          confirmSuccess: 'Cảm ơn bạn! Đơn hàng đã được xác nhận đã nhận.',
          confirmError: 'Không thể cập nhật trạng thái đơn hàng. Vui lòng thử lại.',
          fetchError: 'Không thể tải danh sách đơn hàng.',
        },
        defaultShopName: 'Cửa hàng',
      },
      detailModal: {
        title: 'Chi tiết đơn hàng',
        orderCode: 'Mã đơn hàng',
        status: 'Trạng thái',
        orderDate: 'Ngày đặt hàng',
        payment: 'Thanh toán',
        paymentCOD: 'Thanh toán khi nhận hàng',
        paymentVNPAY: 'VNPAY',
        products: 'Sản phẩm ({count})',
        noImage: 'Không có ảnh',
        category: 'Danh mục',
        categoryFallback: 'Khác',
        loading: 'Đang tải...',
        productFallback: 'Sản phẩm {id}',
        quantity: 'Số lượng',
        lineTotal: 'Thành tiền',
        summary: {
          subtotal: 'Tiền sản phẩm',
          shippingFee: 'Phí vận chuyển',
          voucherDiscount: 'Phí giảm giá từ Voucher',
          total: 'Tổng cộng',
        },
        shippingAddress: {
          title: 'Địa chỉ giao hàng',
          recipient: 'Người nhận',
          phone: 'Số điện thoại',
          detail: 'Địa chỉ chi tiết',
          ward: 'Xã/Phường',
          district: 'Huyện/Quận',
          province: 'Tỉnh/TP',
          country: 'Quốc gia',
        },
        actions: {
          close: 'Đóng',
          cancelOrder: 'Hủy đơn hàng',
        },
        error: 'Không thể tải chi tiết đơn hàng',
      },
      cancelDialog: {
        title: 'Hủy đơn hàng',
        description: 'Vui lòng cho chúng tôi biết lý do bạn muốn hủy đơn hàng',
        reasons: {
          noLongerWant: 'Tôi không muốn mua nữa',
          cheaperElsewhere: 'Tìm được nơi khác rẻ hơn',
          shippingSlow: 'Giao hàng quá lâu',
          mistakenOrder: 'Tôi đặt hàng bị nhầm',
          notAsDescribed: 'Sản phẩm không như mô tả',
          other: 'Lý do khác',
        },
        warning: '⚠️ Hành động này không thể hoàn tác. Bạn có chắc chắn muốn hủy đơn hàng này không?',
        placeholder: 'Nhập lý do hủy đơn hàng của bạn...',
        actions: {
          keep: 'Không hủy',
          confirm: 'Xác nhận hủy',
          processing: 'Đang hủy...',
        },
        toast: {
          missingReason: 'Vui lòng chọn lý do hủy đơn hàng',
          missingCustomReason: 'Vui lòng nhập lý do hủy đơn hàng',
          success: 'Hủy đơn hàng thành công',
          error: 'Không thể hủy đơn hàng',
        },
        reasonValues: {
          noLongerWant: "I don't want to buy anymore",
          cheaperElsewhere: 'Found a cheaper alternative',
          shippingSlow: 'Delivery takes too long',
          mistakenOrder: 'Wrong order',
          notAsDescribed: "Product doesn't match description",
          other: 'Other',
        },
      },
      returnDialog: {
        title: 'Hoàn đơn hàng',
        description: 'Vui lòng chọn lý do bạn muốn hoàn trả đơn hàng này',
        reasons: {
          damaged: 'Sản phẩm bị lỗi hư hỏng',
          mismatch: 'Sản phẩm không đúng mô tả',
          missingAccessories: 'Thiếu phụ kiện / quà tặng',
          wrongVariant: 'Sai kích thước / màu sắc',
          wrongProduct: 'Người bán giao sai sản phẩm',
          other: 'Lý do khác',
        },
        placeholder: 'Nhập lý do hoàn đơn của bạn...',
        notice: 'ⓘ Chúng tôi sẽ liên hệ lại để xác nhận yêu cầu và hướng dẫn quy trình hoàn đơn.',
        actions: {
          cancel: 'Để sau',
          submit: 'Gửi yêu cầu',
          processing: 'Đang gửi...',
        },
        toast: {
          missingReason: 'Vui lòng chọn lý do hoàn đơn',
          missingCustomReason: 'Vui lòng nhập lý do hoàn đơn',
          success: 'Yêu cầu hoàn đơn đã được gửi',
          error: 'Không thể gửi yêu cầu hoàn đơn',
        },
        reasonValues: {
          damaged: 'Product damaged',
          mismatch: 'Product mismatch',
          missingAccessories: 'Missing accessories',
          wrongVariant: 'Wrong size or color',
          wrongProduct: 'Wrong product delivered',
          other: 'Other',
        },
      },
    },
    order: {
      success: 'Đặt hàng thành công',
      details: 'Chi tiết đơn hàng',
      orderId: 'Mã đơn hàng',
      paymentMethod: 'Phương thức thanh toán',
      status: 'Trạng thái',
      codInfo: 'Bạn sẽ thanh toán khi nhận hàng. Vui lòng chuẩn bị tiền mặt hoặc thẻ tín dụng.',
      vnpayInfo: 'Thanh toán đã được xử lý qua VNPAY. Hóa đơn sẽ được gửi đến email của bạn.',
      summary: 'Tóm tắt đơn hàng',
      viewOrders: 'Xem đơn hàng của tôi',
      continueShopping: 'Tiếp tục mua sắm',
      expectedDelivery: 'Thời gian giao hàng dự kiến',
      failed: 'Đặt hàng thất bại',
      retryCheckout: 'Quay lại thanh toán',
      backHome: 'Về trang chủ',
    },
    checkout: {
      title: 'Thanh toán đơn hàng',
      banner: {
        badge: 'HoaLac Handicraft',
        title: 'Thanh toán đơn hàng',
        description: 'Kiểm tra địa chỉ, phương thức thanh toán và hoàn tất đơn hàng của bạn một cách an toàn.',
      },
      review: {
        title: 'Kiểm tra đơn hàng',
        empty: 'Không có sản phẩm nào trong giỏ hàng.',
        headers: {
          product: 'Sản phẩm',
          unitPrice: 'Đơn giá',
          quantity: 'Số lượng',
          subtotal: 'Thành tiền',
        },
        productCode: 'Mã hàng',
        artisan: 'Người bán',
      },
      multiShopSuccess: 'Đặt hàng thành công.',
      vnpayMultiShopMessage: 'Thanh toán VNPay không khả dụng khi đơn hàng chứa sản phẩm từ nhiều cửa hàng. Vui lòng chọn phương thức thanh toán khác.',
      address: {
        title: 'Địa chỉ giao hàng',
        manage: 'Quản lý',
        empty: 'Chưa có địa chỉ giao hàng được lưu.',
        manageCta: 'Quản lý địa chỉ',
        placeholder: 'Chưa chọn địa chỉ',
        defaultBadge: 'Mặc định',
        fallbackName: 'Người nhận',
        fallbackPhone: 'Chưa có số điện thoại',
        fallbackAddress: 'Chưa có địa chỉ chi tiết',
      },
      payment: {
        title: 'Phương thức thanh toán',
        methods: {
          cod: {
            name: 'Thanh toán khi nhận hàng (COD)',
            description: 'Trả tiền mặt khi nhận hàng',
          },
          vnpay: {
            name: 'VNPay',
            description: 'Thanh toán trực tuyến qua VNPay',
          },
        },
      },
      summary: {
        title: 'Đơn hàng của bạn',
        subtotal: 'Tạm tính',
        shipping: 'Phí vận chuyển',
        discount: 'Giảm giá',
        total: 'Tổng cộng',
        voucherLabel: 'Voucher của bạn',
        voucherNone: 'Không sử dụng Voucher',
        voucherPersonal: 'Voucher cá nhân',
        voucherShared: 'Voucher chung',
        voucherEmpty: 'Bạn chưa có Voucher hợp lệ.',
        voucherClear: 'Bỏ chọn Voucher',
        voucherDefault: 'Voucher',
        voucherMin: 'ĐH tối thiểu {amount}',
        voucherMax: 'Giảm tối đa {amount}',
        voucherNotEligible: 'Chưa đạt giá trị tối thiểu.',
        placing: 'Đang đặt hàng...',
        placeOrder: 'Đặt hàng',
        agreement: 'Bằng việc đặt hàng, bạn đồng ý với ',
        agreementLink: 'điều khoản sử dụng',
      },
    },
    auth: {
      common: {
        backLabel: 'Trở về',
        homeLink: 'Trang chủ',
        showPassword: 'Hiện mật khẩu',
        hidePassword: 'Ẩn mật khẩu',
        viLabel: 'Tiếng Việt',
        enLabel: 'English',
      },
      login: {
        heroBadge: 'HoaLacHandicraft',
        heroTitle: 'Chào mừng bạn quay trở lại',
        heroSubtitle: 'Đăng nhập để tiếp tục khám phá những sản phẩm thủ công tinh xảo đến từ Hòa Lạc.',
        welcomeTag: 'Chào mừng trở lại',
        title: 'Đăng nhập',
        subtitle: 'Nhập thông tin bên dưới để tiếp tục trải nghiệm tại HoaLacHandicraft.',
        usernameLabel: 'Tên đăng nhập',
        usernamePlaceholder: 'Tên đăng nhập',
        passwordLabel: 'Mật khẩu',
        passwordPlaceholder: 'Mật khẩu',
        remember: 'Ghi nhớ đăng nhập',
        forgot: 'Quên mật khẩu?',
        submit: 'Đăng nhập',
        submitting: 'Đang đăng nhập...',
        registerPrompt: 'Chưa có tài khoản?',
        registerLink: 'Đăng ký',
        toastSuccess: 'Đăng nhập thành công!',
        toastInvalid: 'Tên đăng nhập hoặc mật khẩu không đúng.',
        toastError: 'Không thể đăng nhập. Vui lòng thử lại.',
        toastInactive: 'Tài khoản đã bị khóa do vi phạm chính sách của website. Vui lòng liên hệ Hoalachandicraft@gmail.com để biết thêm thông tin.',
      },
      register: {
        heroBadge: 'HoaLacHandicraft',
        heroTitle: 'Chào mừng đến với cộng đồng thủ công Việt',
        heroSubtitle: 'Kết nối cùng nghệ nhân Hòa Lạc, khám phá tinh hoa làng nghề và lưu giữ nét đẹp truyền thống.',
        startTag: 'Bắt đầu hành trình',
        title: 'Tạo tài khoản mới',
        subtitle: 'Nhập thông tin dưới đây để gia nhập cộng đồng HoaLacHandicraft.',
        form: {
          emailLabel: 'Email',
          emailPlaceholder: 'Email của bạn',
          usernameLabel: 'Tên đăng nhập',
          usernamePlaceholder: 'Tên đăng nhập của bạn',
          phoneLabel: 'Số điện thoại',
          phonePlaceholder: 'Số điện thoại của bạn',
          displayNameLabel: 'Họ và tên',
          displayNamePlaceholder: 'Họ và tên của bạn',
          dobLabel: 'Ngày sinh',
          dobDay: 'Ngày',
          dobMonth: 'Tháng',
          dobYear: 'Năm',
          passwordLabel: 'Mật khẩu',
          passwordPlaceholder: 'Mật khẩu',
          confirmPasswordLabel: 'Xác nhận mật khẩu',
          confirmPasswordPlaceholder: 'Xác nhận mật khẩu',
        },
        buttons: {
          submit: 'Đăng ký',
          submitting: 'Đang đăng ký...',
        },
        cta: {
          haveAccount: 'Đã có tài khoản?',
          loginLink: 'Đăng nhập',
        },
        otp: {
          title: 'Xác thực OTP',
          description: 'Vui lòng nhập mã xác thực được gửi đến email của bạn',
          notReceived: 'Không nhận được mã?',
          resendReady: 'Gửi lại mã',
          resendCountdown: 'Gửi lại mã ({seconds}s)',
          confirmButton: 'Xác nhận',
          closeAria: 'Đóng cửa sổ',
        },
        toasts: {
          registerSuccess: 'Đăng ký thành công! Vui lòng kiểm tra email để lấy mã OTP.',
          duplicate: 'Email hoặc tên đăng nhập đã tồn tại!',
          registerError: 'Không thể đăng ký. Vui lòng thử lại.',
          waitBeforeResend: 'Vui lòng chờ {seconds}s trước khi gửi lại mã.',
          resendInfo: 'Đang gửi lại mã OTP...',
          resendSuccess: 'Đã gửi lại mã OTP thành công!',
          resendError: 'Không thể gửi lại mã OTP. Vui lòng thử lại sau.',
          otpSuccess: 'Mã OTP đúng, đăng ký thành công! Vui lòng đăng nhập để tiếp tục.',
          otpError: 'Xác thực OTP thất bại.',
        },
        errors: {
          usernameLength: 'Tên đăng nhập phải từ 3–30 ký tự.',
          passwordLength: 'Mật khẩu phải có ít nhất 6 ký tự.',
          passwordMismatch: 'Mật khẩu xác nhận không khớp.',
          emailInvalid: 'Email không hợp lệ.',
          phoneRequired: 'Vui lòng nhập số điện thoại hợp lệ.',
          phoneInvalid: 'Số điện thoại không đúng định dạng. Ví dụ: 0901234567, +84901234567.',
          phoneInvalid84: 'Số điện thoại +84 phải có đầu số 3, 5, 7, 8 hoặc 9 và 8 chữ số tiếp theo.',
          displayNameLength: 'Tên hiển thị không được dài quá 50 ký tự.',
          dobIncomplete: 'Vui lòng chọn đầy đủ Ngày/Tháng/Năm.',
          dobInvalid: 'Ngày sinh không hợp lệ.',
          dobFuture: 'Ngày sinh không thể ở tương lai.',
          dobTooOld: 'Ngày sinh không hợp lệ.',
          dobNonexistent: 'Ngày sinh không tồn tại. Vui lòng chọn lại.',
        },
      },
    },
    general: {
      errorPrefix: 'Lỗi: ',
      unknownError: 'Đã xảy ra lỗi không xác định.',
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      shop: 'Shop',
      blog: 'Blog',
      contact: 'Contact',
      policy: 'Policies',
    },
    footer: {
      contactTitle: 'Contact',
      address: 'Hoa Lac, Thach That, Ha Noi',
      email: 'Hoalachandicraft@gmail.com',
      phone: '0921643475',
      store: {
        title: 'Shop',
        dragonfly: 'Thach Xa bamboo dragonfly',
        fan: 'Quang Son paper fan',
        bamboo: 'Bamboo weaving',
        allProducts: 'View all products',
      },
      policy: {
        title: 'Policies',
      },
      explore: {
        title: 'Discover',
        blog: 'Craft village news',
        collections: 'Product collections',
      },
      copyright: 'Copyright © 2025 Hoalachandicraft · All Rights Reserved',
    },
    header: {
      searchPlaceholder: 'Search...',
      login: 'Sign in',
      profile: 'My account',
      orders: 'Orders',
      logout: 'Sign out',
      notificationsEmpty: 'No new notifications.',
      cartTooltip: 'Cart',
      artisanDashboard: 'Manage store',
    },
    pageTitles: {
      brand: 'HoaLac Handicraft',
      home: 'Home',
      about: 'About us',
      shop: 'Shop',
      blog: 'Blog',
      blogDetail: 'Blog detail',
      contact: 'Contact',
      policy: 'Policy',
      cart: 'Shopping cart',
      checkout: 'Checkout',
      orderHistory: 'Order history',
      orderTracking: 'Order tracking',
      orderSuccess: 'Order success',
      paymentResult: 'Payment result',
      profile: 'My account',
      login: 'Sign in',
      register: 'Register',
      forgotPassword: 'Forgot password',
      productDetail: 'Product detail',
      collectionDetail: 'Collection',
      artisanShop: 'Artisan shop',
      artisanDashboard: 'Artisan dashboard',
      adminDashboard: 'Admin dashboard',
      storytellingDetail: 'Storytelling',
      notFound: 'Page not found',
    },
    home: {
      collections: {
        title: 'Product collections',
        description: 'Explore curated collections where every design captures the spirit of Hoa Lac craftsmanship.',
        empty: 'No products available.',
        badge: 'Collections',
        cta: 'Discover now',
        error: 'Unable to load collections.',
      },
      hero: {
        initialTitle: 'Hoa Lac traditional artistry',
        initialDescription: 'Where masterful hands meet treasured memories of the craft village. Every detail carries the desire to share Vietnamese identity with the world. We cherish the stories behind each piece so you can feel tradition breathing within modern spaces.',
        overlayTitle: 'Welcome to the\nHoaLac Handicraft website',
        cta: 'Explore',
        introTitle: 'Every heartbeat of the craft village and every artisan story is woven with care and pride.',
        introDescription: 'From the early days of the village, the people of Hoa Lac have preserved their creative spirit so every creation is more than an object—it carries the memory of its homeland. Generations of artisans pass down techniques, cultural breath, and the belief that tradition ties the past to the present.',
        values: {
          heritage: {
            title: 'Craft legacy preserved',
            description: 'Across generations, crafting secrets are shared by the warm hearth. They celebrate the rhythm of tools, the scent of sun-dried bamboo, and the pride of a finished piece.',
          },
          culture: {
            title: 'Cultural colors',
            description: 'Each motif is a symbol of seasons, beliefs, and way of life. Artisans choose colors by feeling, creating vibrant yet harmonious works that mirror village rhythms.',
          },
          contemporary: {
            title: 'Contemporary breath',
            description: 'While the world changes, Hoa Lac keeps its soul yet constantly innovates. New designs focus on usability, bringing traditional craft closer to modern living.',
          },
        },
        closing: 'Our journey is to tell the most sincere stories about the people of Hoa Lac—those who devote their lives to preserving Vietnamese identity through their craft.',
      },
      featured: {
        badge: 'Curated highlights',
        title: 'Featured products',
        description: 'Beloved handcrafted pieces that showcase meticulous Hoa Lac artistry paired with time-honored materials.',
        cta: 'Visit the shop',
      },
      contactSection: {
        badge: 'Connect with Hoa Lac',
        title: 'Contact Us',
        description: 'We are ready to accompany you on the journey of exploring and preserving traditional craft values.',
        namePlaceholder: 'Full name',
        emailPlaceholder: 'Email',
        phonePlaceholder: 'Phone number',
        messagePlaceholder: 'Share a message with us',
        cta: 'Contact us',
        note: 'Or reach us directly through the channels below',
        hotlineLabel: 'Hotline',
      },
      artisanCraft: {
        badge: 'Craft village journey',
        title: 'Hoa Lac artisan space',
        description: 'Follow the rhythm of artisan life, where every carving and brushstroke is cherished to preserve traditional essence.',
        slides: {
          first: {
            title: 'Discover the craft village',
            subtitle: 'Vietnamese craftsmanship',
            content: 'Each piece tells a story of artisan hands and the traditional values they preserve and innovate.',
          },
          second: {
            title: 'Connect with artisans',
            subtitle: 'From hands to hearts',
            content: 'Meet talented makers who bring handcrafted creations closer to everyday life.',
          },
          third: {
            title: 'Preserve and grow',
            subtitle: 'A living heritage',
            content: 'Join the effort to sustain the craft village and share Vietnamese handcraft with the world.',
          },
        },
        sliderTag: 'Tradition & Modernity',
      },
      discover: {
        badge: 'Craft village stories',
        title: 'Discover Hoa Lac',
        description: 'Stories, events, and inspirations from the journey of preserving and elevating traditional craftsmanship.',
        cta: 'View all articles',
        cardTag: 'Discover',
      },
    },
    about: {
      breadcrumbHome: 'Home',
      breadcrumbCurrent: 'About Us',
      cloudIntro: {
        description: 'Hoa Lac is more than a place—it is a gathering of masterful hands where every wood grain, bamboo fiber, and ceramic shard carries the spirit of its artisans and their cultural heritage.',
      },
      mission: {
        title: 'Our mission',
        items: {
          first: 'Preserve the heritage of the Hoa Lac craft village',
          second: 'Connect artisans with the community that loves handcrafts',
          third: 'Share the beauty of Vietnamese culture through every creation',
        },
      },
      whyUs: {
        titleLine1: 'Why choose',
        titleLine2: 'Hoa Lac Handicraft?',
        reasons: {
          first: 'Authentic & handcrafted: Every piece is meticulously handmade, carrying the soul of Vietnamese artisans.',
          second: 'Bridging tradition & modern life: We honor timeless designs while adapting them for today’s living spaces.',
          third: 'Stories behind each piece: Every item reflects a craft village, a dedicated artisan, and a cultural pride.',
          fourth: 'Meaningful & sustainable: We champion sustainable growth, stand beside artisans, and spread craft values to the community.',
        },
      },
    },
    shop: {
      loading: 'Loading products...',
      empty: 'No products available.',
      banner: {
        title: 'Welcome to the HoaLac Handicraft boutique',
        subtitle: 'A curated collection of refined handcrafted pieces',
        cta: 'Discover products',
      },
      filter: {
        allProductsHeading: 'All products',
        allLabel: 'All',
        unknownCategory: 'Untitled',
        searchPlaceholder: 'Search products...',
        sortButton: 'Sort',
        sortTitle: 'Sort by:',
        scrollLeft: 'Scroll left',
        scrollRight: 'Scroll right',
        sort: {
          default: 'Default',
          lowToHigh: 'Price: low to high',
          highToLow: 'Price: high to low',
          aToZ: 'Name A -> Z',
          zToA: 'Name Z -> A',
        },
        searchButton: 'Search',
      },
    },
    blog: {
      breadcrumb: {
        home: 'Home',
        current: 'Blog',
      },
      hero: {
        badge: 'Craft village news',
        emptyHighlights: 'Featured stories will appear here soon.',
        emptyList: 'No articles have been published yet. Please check back later.',
      },
      featured: {
        badge: 'Featured posts',
        title: 'Recent articles',
        countLabel: 'Showing {count} of {total} articles',
        readMore: 'Read article',
        empty: 'More stories will be published soon.',
      },
      updating: 'Updating',
      authorFallback: 'G90 Editorial',
      loadError: 'Unable to load articles.',
    },
    blogDetail: {
      missing: 'The article does not exist.',
      loadError: 'Unable to load the article.',
      backToBlog: 'Back to blog',
      byLabel: 'By',
      postedIn: 'Posted in',
      mainContent: 'Main content',
      statusLabel: 'Status',
      idLabel: 'Article ID',
      statusFallback: 'Active',
      categoryFallback: 'News',
      contentUpdating: 'Content will be updated soon.',
      relatedBadge: 'You may also like',
      relatedTitle: 'Related articles',
      viewAll: 'View all',
      relatedSummaryFallback: 'Discover more about traditional craftsmanship stories.',
    },
    productCard: {
      fallbackDescription: 'Handcrafted piece inspired by tradition',
      sold: '{count} sold',
      rating: '({count})',
      priceLabel: 'Price',
      stock: '{stock} items left',
      viewDetail: 'View detail',
      addToCart: 'Add to cart',
      buyNow: 'Buy now',
      priceSuffix: ' VND',
      soldOut: 'Sold out',
    },
    relation: {
      title: 'Similar products',
      subtitle: 'Explore more refined handcrafted creations',
      loading: 'Loading related products...',
    },
    contact: {
      title: 'Contact',
      description: 'Feel free to drop us a message. The HoaLac Handicraft team is ready to listen and support you.',
      form: {
        name: 'Full name',
        email: 'Email',
        phone: 'Phone number',
        message: 'Message',
        submit: 'Send message',
        sending: 'Sending...',
        validation: {
          nameRequired: 'Please enter your full name.',
          emailRequired: 'Please enter your email.',
          emailInvalid: 'Please enter a valid email address.',
          phoneRequired: 'Please enter your phone number.',
          phoneInvalid: 'Phone number must contain 9-11 digits.',
          messageRequired: 'Please enter a message.',
          messageLength: 'Message should have at least {min} characters.',
        },
      },
      infoTitle: 'Contact information',
      office: 'Office',
      address: 'Hoa Lac Hi-Tech Park, Thach That, Ha Noi',
      phone: 'Phone',
      emailLabel: 'Email',
      hoursTitle: 'Working hours',
      hoursValue: 'Monday - Friday: 8:30 AM - 5:30 PM',
    },
    policy: {
      title: 'Policies',
      updated: 'Last updated: November 2025',
      privacyTitle: 'Privacy policy',
      privacyContent: 'We are committed to protecting your personal data and only use it to deliver our services. All information is encrypted and stored securely.',
      shippingTitle: 'Shipping policy',
      shippingContent: 'Orders are processed within 24 hours and delivered within 3-5 business days nationwide via trusted partners.',
      returnTitle: 'Return policy',
      returnContent: 'You can return products within 7 days of delivery if they are defective or damaged during transportation.',
    },
    cart: {
      title: 'Your cart',
      empty: 'Your cart is empty.',
      headerProduct: 'Product',
      headerQuantity: 'Quantity',
      headerPrice: 'Unit price',
      headerSubtotal: 'Subtotal',
      summaryTitle: 'Order summary',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      total: 'Total',
      checkout: 'Proceed to checkout',
      continueShopping: 'Continue shopping',
      itemsCount: '{count} items',
      updating: 'Updating...',
      remove: 'Remove',
      banner: {
        title: 'Your cart',
        description: 'Review your items before checkout to make sure everything looks right.',
      },
      emptyInfo: 'Your cart is empty—add some handmade treasures to continue!',
      unavailableNotice: 'This item is out of stock or no longer available.',
      unavailableOnly: 'Your cart currently contains only out-of-stock items. Please remove them before continuing.',
      unavailableConfirm: 'Some items in your cart are out of stock. Continue to checkout with the remaining items?',
      shopFallback: 'Shop',
      shopCodeLabel: 'Shop code',
      visitShop: 'Visit shop',
      shopSubtotal: 'Order total',
      checkoutShop: 'Order from this shop',
      checkoutShopDisabled: 'All items from this shop are unavailable.',
      checkoutContextLabel: 'Selected shop',
      selectAll: 'Select all',
      selectedSummary: 'Selected {count} items - {amount}',
      emptySelection: 'Choose items to see totals.',
      shopSelectLabel: 'Select this shop',
      itemSelectLabel: 'Select this item',
      multipleShopsSelected: '{count} shops selected',
      selectedCountLabel: 'Selected items',
      selectedAmountLabel: 'Subtotal',
    },
    messages: {
      loginRequired: 'Please log in to continue.',
      loginToAddCart: 'Sign in to add items to your cart.',
      loginToBuyNow: 'Sign in to buy now.',
      addedToCart: 'Product added to cart.',
      addedToCartRedirect: 'Product added. Redirecting to cart...',
      addToCartError: 'Could not add the product to cart.',
      cartLoadError: 'Unable to load your cart.',
      cartUpdateSuccess: 'Quantity updated.',
      cartUpdateError: 'Failed to update quantity.',
      cartRemoveSuccess: 'Item removed from cart.',
      cartRemoveError: 'Failed to remove item.',
      checkoutComingSoon: 'Checkout is coming soon.',
      cartEmpty: 'Your cart is empty.',
      addressRequired: 'Please select a shipping address.',
      orderSuccess: 'Order placed successfully.',
      orderError: 'Could not place the order. Please try again.',
      wishlistAdded: 'Added to your wishlist.',
      wishlistRemoved: 'Removed from your wishlist.',
      wishlistLoginRequired: 'Sign in to manage your wishlist.',
      removedUnavailable: 'Some items were out of stock and removed from checkout.',
      redirectVnpay: 'Redirecting to VNPAY...',
      voucherLoadError: 'Unable to load vouchers.',
      contactSuccess: 'Thank you! We will reach out soon.',
      contactError: 'We could not send your message. Please try again later.',
    },
    orderHistory: {
      page: {
        title: 'Order history',
        breadcrumbHome: 'Home',
        breadcrumbCurrent: 'Order history',
        stats: {
          totalSpentTitle: 'Total spent',
          totalSpentCaption: 'Based on current filters',
          ordersShownTitle: 'Orders shown',
          ordersShownCaption: 'On this page',
        },
        filters: {
          title: 'Advanced filters',
          reset: 'Clear filters',
          startDateLabel: 'From date',
          endDateLabel: 'To date',
          selectDay: 'Day',
          selectMonth: 'Month',
          selectYear: 'Year',
          paymentMethodLabel: 'Payment method',
          paymentMethod: {
            all: 'All',
            COD: 'Cash on delivery',
            VNPAY: 'VNPAY',
          },
        },
      },
      statuses: {
        all: 'All',
        WaitingForPickup: 'Awaiting confirmation',
        Shipping: 'In transit',
        Completed: 'Delivered',
        Cancelled: 'Cancelled',
        Paid: 'Paid',
        paidWaitingConfirmation: 'Paid, awaiting shop confirmation',
        paidConfirmedAwaitingShipping: 'Order confirmed, the shop is preparing to hand it over to the carrier',
        default: 'Unknown',
      },
      loading: 'Loading...',
      pagination: {
        prev: 'Previous',
        next: 'Next',
        label: 'Page {current}/{total}',
      },
      empty: {
        title: 'No orders yet',
      },
      list: {
        orderLabel: 'Order: {orderNumber}',
        paymentMethodLabel: 'Payment method',
        paymentMethodCOD: 'Cash on delivery',
        paymentMethodVNPAY: 'VNPAY',
        totalLabel: 'Total',
        viewShop: 'View shop',
        actions: {
          viewDetail: 'View details',
          requestReturn: 'Return order',
          continuePayment: 'Continue payment',
          confirmReceived: 'Mark as received',
          confirming: 'Confirming...',
          cancelOrder: 'Cancel order',
        },
        toast: {
          continueProcessing: 'Processing payment...',
          continueMissingUrl: 'Unable to retrieve payment link. Please try again.',
          continueError: 'Something went wrong while continuing the payment. Please try again.',
          confirmSuccess: 'Thank you! The order has been marked as received.',
          confirmError: 'Unable to update the order status. Please try again.',
          fetchError: 'Unable to load the order list.',
        },
        defaultShopName: 'Shop',
      },
      detailModal: {
        title: 'Order details',
        orderCode: 'Order code',
        status: 'Status',
        orderDate: 'Order date',
        payment: 'Payment',
        paymentCOD: 'Cash on delivery',
        paymentVNPAY: 'VNPAY',
        products: 'Products ({count})',
        noImage: 'No image',
        category: 'Category',
        categoryFallback: 'Other',
        loading: 'Loading...',
        productFallback: 'Product {id}',
        quantity: 'Quantity',
        lineTotal: 'Line total',
        summary: {
          subtotal: 'Product amount',
          shippingFee: 'Shipping fee',
          voucherDiscount: 'Voucher discount fee',
          total: 'Grand total',
        },
        shippingAddress: {
          title: 'Shipping address',
          recipient: 'Recipient',
          phone: 'Phone number',
          detail: 'Address',
          ward: 'Ward',
          district: 'District',
          province: 'Province/City',
          country: 'Country',
        },
        actions: {
          close: 'Close',
          cancelOrder: 'Cancel order',
        },
        error: 'Unable to load order details',
      },
      cancelDialog: {
        title: 'Cancel order',
        description: 'Please let us know why you want to cancel this order',
        reasons: {
          noLongerWant: 'I no longer wish to buy',
          cheaperElsewhere: 'Found a cheaper alternative',
          shippingSlow: 'Delivery is taking too long',
          mistakenOrder: 'I placed the wrong order',
          notAsDescribed: 'The product differs from the description',
          other: 'Other',
        },
        warning: '⚠️ This action cannot be undone. Are you sure you want to cancel this order?',
        placeholder: 'Enter your cancellation reason...',
        actions: {
          keep: 'Keep order',
          confirm: 'Confirm cancellation',
          processing: 'Cancelling...',
        },
        toast: {
          missingReason: 'Please choose a cancellation reason',
          missingCustomReason: 'Please enter your cancellation reason',
          success: 'Order cancelled successfully',
          error: 'Unable to cancel the order',
        },
        reasonValues: {
          noLongerWant: "I don't want to buy anymore",
          cheaperElsewhere: 'Found a cheaper alternative',
          shippingSlow: 'Delivery takes too long',
          mistakenOrder: 'Wrong order',
          notAsDescribed: "Product doesn't match description",
          other: 'Other',
        },
      },
      returnDialog: {
        title: 'Return order',
        description: 'Please choose why you want to return this order',
        reasons: {
          damaged: 'The product is damaged',
          mismatch: 'The product does not match the description',
          missingAccessories: 'Missing accessories or gifts',
          wrongVariant: 'Wrong size or color',
          wrongProduct: 'The seller delivered the wrong product',
          other: 'Other',
        },
        placeholder: 'Enter your return reason...',
        notice: 'ⓘ We will contact you to confirm the request and guide you through the return process.',
        actions: {
          cancel: 'Maybe later',
          submit: 'Submit request',
          processing: 'Submitting...',
        },
        toast: {
          missingReason: 'Please choose a return reason',
          missingCustomReason: 'Please enter your return reason',
          success: 'Return request submitted',
          error: 'Unable to submit the return request',
        },
        reasonValues: {
          damaged: 'Product damaged',
          mismatch: 'Product mismatch',
          missingAccessories: 'Missing accessories',
          wrongVariant: 'Wrong size or color',
          wrongProduct: 'Wrong product delivered',
          other: 'Other',
        },
      },
    },
    profile: {
      common: {
        sending: 'Sending...',
        processing: 'Processing...',
        saving: 'Saving...',
        cancel: 'Cancel',
      },
      changePassword: {
        title: 'Change password',
        emailLabel: 'Email',
        sendOtp: 'Send OTP',
        otpLabel: 'OTP',
        otpPlaceholder: 'Enter OTP code',
        otpRequired: 'Please enter the OTP code.',
        passwordRequired: 'Please complete the password fields.',
        passwordMismatch: 'Password confirmation does not match.',
        passwordRule: 'Password must be at least 6 characters, with 1 uppercase letter and 1 special character.',
        newPasswordLabel: 'New password',
        newPasswordPlaceholder: 'Enter new password',
        confirmPasswordLabel: 'Confirm password',
        confirmPasswordPlaceholder: 'Re-enter password',
        otpSent: 'The OTP has been sent to your email.',
        emailNotFound: 'Email does not exist in the system.',
        resetSuccess: 'Password updated successfully.',
        otpInvalid: 'The OTP is invalid or has expired.',
        submit: 'Change password',
      },
      errors: {
        fetchUser: 'Unable to retrieve user information.',
      },
      avatar: {
        sizeError: 'Image size must not exceed 5MB.',
        typeError: 'Please select an image file.',
        updateSuccess: 'Profile photo updated successfully!',
        updateError: 'Unable to update profile photo.',
        view: 'View photo',
        change: 'Change photo',
      },
      info: {
        title: 'Account information',
        nameLabel: 'Name',
        phoneLabel: 'Phone number',
        emailLabel: 'Email',
        usernameLabel: 'Username',
        dobLabel: 'Date of birth',
        dobPlaceholder: 'dd/mm/yyyy',
        dobDayPlaceholder: 'dd',
        dobMonthPlaceholder: 'mm',
        dobYearPlaceholder: 'yyyy',
        dobInvalid: 'Invalid date of birth.',
        dobAgeLimit: 'Date of birth exceeds the allowed age range.',
        updateSuccess: 'Profile updated successfully!',
        updateError: 'Unable to update profile.',
        editButton: 'Edit details',
        saveButton: 'Save details',
      },
      address: {
        title: 'Shipping addresses',
        addButton: 'Add address',
        closeButton: 'Close',
        empty: 'No addresses saved yet.',
        detailFallback: 'No detailed address provided.',
        defaultBadge: 'Default',
        editButton: 'View / Edit',
        deleteButton: 'Delete',
        singleDefaultNotice: 'You only have one address; it will be set as default.',
        validation: {
          missingFields: 'Please select province, district, ward, and enter the detailed address.',
          invalidProvinceDistrict: 'Invalid province or district.',
        },
        updateSuccess: 'Address updated successfully!',
        createSuccess: 'Address added successfully!',
        saveError: 'Unable to save address.',
        deleteSuccess: 'Address deleted successfully.',
        deleteError: 'Unable to delete address.',
        loadProvincesError: 'Unable to load provinces.',
        loadDistrictsError: 'Unable to load districts.',
        loadWardsError: 'Unable to load wards.',
        form: {
          recipientLabel: 'Recipient name',
          phoneLabel: 'Phone number',
          provinceLabel: 'Province/City',
          provinceLoading: 'Loading provinces...',
          provincePlaceholder: 'Select a province/city',
          districtLabel: 'District',
          districtSelectProvince: 'Please select a province first',
          districtLoading: 'Loading districts...',
          districtPlaceholder: 'Select a district',
          wardLabel: 'Ward',
          wardSelectDistrict: 'Please select a district first',
          wardLoading: 'Loading wards...',
          wardPlaceholder: 'Select a ward',
          detailLabel: 'Address line 1',
          detail2Label: 'Address line 2 (optional)',
          defaultCheckbox: 'Set as default address',
          saving: 'Saving...',
          saveButton: 'Save address',
        },
        deleteModal: {
          title: 'Delete address',
          message: 'Are you sure you want to delete this address? This action cannot be undone.',
          cancel: 'Cancel',
          confirm: 'Delete',
        },
      },
      loading: {
        title: 'Loading your information...',
        subtitle: 'Please wait a moment',
      },
      sidebar: {
        accountInfo: 'Account information',
        orderHistory: 'Order history',
        wishlist: 'Saved products',
        artisanShop: 'My shop',
        artisanRegister: 'Become a seller',
        changePassword: 'Change password',
        logout: 'Sign out',
      },
      artisanApplication: {
        status: {
          pending: {
            label: 'Pending review',
            description: 'Your application is under review by our administrators. Please wait a little longer.',
          },
          approved: {
            label: 'Approved',
            description: 'Your application has been approved. You can start managing your store.',
          },
          rejected: {
            label: 'Rejected',
            description: 'Your application was rejected. Please review the reason and contact support if needed.',
          },
          unknown: {
            label: 'Unknown',
            description: '',
          },
        },
      },
    },
    order: {
      success: 'Order Placed Successfully',
      details: 'Order Details',
      orderId: 'Order ID',
      paymentMethod: 'Payment Method',
      status: 'Status',
      codInfo: 'You will pay when receiving your order. Please prepare cash or credit card.',
      vnpayInfo: 'Payment has been processed through VNPAY. An invoice will be sent to your email.',
      summary: 'Order Summary',
      viewOrders: 'View My Orders',
      continueShopping: 'Continue Shopping',
      expectedDelivery: 'Expected Delivery Time',
      failed: 'Order Failed',
      retryCheckout: 'Return to Checkout',
      backHome: 'Back to Home',
    },
    checkout: {
      title: 'Checkout',
      banner: {
        badge: 'HoaLac Handicraft',
        title: 'Complete your order',
        description: 'Review your address, payment method, and finalize your order confidently.',
      },
      review: {
        title: 'Order review',
        empty: 'There are no items in your cart.',
        headers: {
          product: 'Product',
          unitPrice: 'Unit price',
          quantity: 'Quantity',
          subtotal: 'Subtotal',
        },
        productCode: 'SKU',
        artisan: 'Seller',
      },
      multiShopSuccess: 'Order placed successfully.',
      vnpayMultiShopMessage: 'VNPay checkout is unavailable when your order contains items from multiple shops. Please choose another payment method.',
      address: {
        title: 'Shipping address',
        manage: 'Manage',
        empty: 'No saved shipping addresses yet.',
        manageCta: 'Manage addresses',
        placeholder: 'No address selected',
        defaultBadge: 'Default',
        fallbackName: 'Recipient',
        fallbackPhone: 'Phone number unavailable',
        fallbackAddress: 'No detailed address provided',
      },
      payment: {
        title: 'Payment method',
        methods: {
          cod: {
            name: 'Cash on delivery (COD)',
            description: 'Pay in cash when the order arrives',
          },
          vnpay: {
            name: 'VNPay',
            description: 'Secure online payment via VNPay',
          },
        },
      },
      summary: {
        title: 'Your order',
        subtotal: 'Subtotal',
        shipping: 'Shipping fee',
        discount: 'Discount',
        total: 'Total',
        voucherLabel: 'Your vouchers',
        voucherNone: 'Do not use a voucher',
        voucherPersonal: 'Personal vouchers',
        voucherShared: 'Shared vouchers',
        voucherEmpty: 'No eligible vouchers available.',
        voucherClear: 'Remove voucher',
        voucherDefault: 'Voucher',
        voucherMin: 'Min order {amount}',
        voucherMax: 'Max discount {amount}',
        voucherNotEligible: 'Minimum order value not reached.',
        placing: 'Placing order...',
        placeOrder: 'Place order',
        agreement: 'By placing the order, you agree to ',
        agreementLink: 'the terms of use',
      },
    },
    auth: {
      common: {
        backLabel: 'Back',
        homeLink: 'Home',
        showPassword: 'Show password',
        hidePassword: 'Hide password',
        viLabel: 'Vietnamese',
        enLabel: 'English',
      },
      login: {
        heroBadge: 'HoaLacHandicraft',
        heroTitle: 'Welcome back',
        heroSubtitle: 'Sign in to keep exploring the handcrafted creations from Hoa Lac.',
        welcomeTag: 'Welcome back',
        title: 'Sign in',
        subtitle: 'Enter your credentials below to continue your experience at HoaLacHandicraft.',
        usernameLabel: 'Username',
        usernamePlaceholder: 'Username',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Password',
        remember: 'Remember me',
        forgot: 'Forgot password?',
        submit: 'Sign in',
        submitting: 'Signing in...',
        registerPrompt: 'Don’t have an account?',
        registerLink: 'Sign up',
        toastSuccess: 'Signed in successfully!',
        toastInvalid: 'Incorrect username or password.',
        toastError: 'Unable to sign in. Please try again.',
        toastInactive: 'Your account has been locked for violating our policies. Please contact Hoalachandicraft@gmail.com for more information.',
      },
      register: {
        heroBadge: 'HoaLacHandicraft',
        heroTitle: 'Welcome to the Vietnamese craft community',
        heroSubtitle: 'Connect with Hoa Lac artisans, discover traditional craftsmanship, and preserve cultural values.',
        startTag: 'Begin your journey',
        title: 'Create a new account',
        subtitle: 'Fill in the information below to join the HoaLacHandicraft community.',
        form: {
          emailLabel: 'Email',
          emailPlaceholder: 'Your email',
          usernameLabel: 'Username',
          usernamePlaceholder: 'Your username',
          phoneLabel: 'Phone number',
          phonePlaceholder: 'Your phone number',
          displayNameLabel: 'Full name',
          displayNamePlaceholder: 'Your full name',
          dobLabel: 'Date of birth',
          dobDay: 'Day',
          dobMonth: 'Month',
          dobYear: 'Year',
          passwordLabel: 'Password',
          passwordPlaceholder: 'Password',
          confirmPasswordLabel: 'Confirm password',
          confirmPasswordPlaceholder: 'Confirm password',
        },
        buttons: {
          submit: 'Sign up',
          submitting: 'Signing up...',
        },
        cta: {
          haveAccount: 'Already have an account?',
          loginLink: 'Sign in',
        },
        otp: {
          title: 'OTP verification',
          description: 'Enter the verification code sent to your email.',
          notReceived: 'Didn’t receive the code?',
          resendReady: 'Resend code',
          resendCountdown: 'Resend code ({seconds}s)',
          confirmButton: 'Confirm',
          closeAria: 'Close dialog',
        },
        toasts: {
          registerSuccess: 'Registration successful! Please check your email for the OTP code.',
          duplicate: 'Email or username already exists!',
          registerError: 'Unable to register. Please try again.',
          waitBeforeResend: 'Please wait {seconds}s before requesting a new code.',
          resendInfo: 'Sending the OTP again...',
          resendSuccess: 'OTP resent successfully!',
          resendError: 'Unable to resend the OTP. Please try again later.',
          otpSuccess: 'OTP verified successfully! Please sign in to continue.',
          otpError: 'OTP verification failed.',
        },
        errors: {
          usernameLength: 'Username must be between 3 and 30 characters.',
          passwordLength: 'Password must be at least 6 characters.',
          passwordMismatch: 'Password confirmation does not match.',
          emailInvalid: 'Invalid email address.',
          phoneRequired: 'Please enter a valid phone number.',
          phoneInvalid: 'Phone number format is invalid. Examples: 0901234567, +84901234567.',
          phoneInvalid84: 'Phone numbers starting with +84 must use 3, 5, 7, 8, or 9 and include 8 following digits.',
          displayNameLength: 'Display name cannot exceed 50 characters.',
          dobIncomplete: 'Please select the full day, month, and year.',
          dobInvalid: 'Invalid date of birth.',
          dobFuture: 'Date of birth cannot be in the future.',
          dobTooOld: 'Invalid date of birth.',
          dobNonexistent: 'The selected date of birth does not exist. Please try again.',
        },
      },
    },
    general: {
      errorPrefix: 'Error: ',
      unknownError: 'An unknown error occurred.',
    },
  },
};

export const LanguageContext = createContext({
  language: 'vi',
  changeLanguage: () => {},
  t: (key) => key,
});

const getStoredLanguage = () => {
  if (typeof window === 'undefined') return 'vi';
  return localStorage.getItem('app_language') || 'vi';
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getStoredLanguage);

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
  }, []);

  const translate = useCallback(
    (key, replacements = {}) => {
      if (!key) return '';

      const rawValue = key
        .split('.')
        .reduce((acc, part) => {
          if (acc && typeof acc === 'object') {
            return acc[part];
          }
          return undefined;
        }, translations[language]);

      if (typeof rawValue !== 'string') {
        return key;
      }

      return Object.keys(replacements).reduce(
        (acc, placeholder) => acc.replace(`{${placeholder}}`, replacements[placeholder]),
        rawValue,
      );
    },
    [language],
  );

  const value = useMemo(
    () => ({
      language,
      changeLanguage,
      t: translate,
    }),
    [language, changeLanguage, translate],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

LanguageProvider.propTypes = {
  children: PropTypes.node.isRequired,
};
