import React, {
  createContext,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react';
import PropTypes from 'prop-types';

const translations = {
  vi: {
    nav: {
      home: 'Trang chủ',
      about: 'Về chúng tôi',
      shop: 'Cửa hàng',
      blog: 'Bài viết',
      contact: 'Liên hệ',
      policy: 'Chính sách',
    },
    header: {
      searchPlaceholder: 'Tìm kiếm...',
      login: 'Đăng nhập',
      profile: 'Tài khoản của tôi',
      orders: 'Đơn hàng',
      logout: 'Đăng xuất',
      notificationsEmpty: 'Không có thông báo mới.',
      cartTooltip: 'Giỏ hàng',
    },
    home: {
      collections: {
        title: 'Bộ sưu tập sản phẩm',
        description: 'Khám phá những bộ sưu tập được tuyển chọn kỹ lưỡng, nơi mỗi thiết kế đều mang dấu ấn của làng nghề Hòa Lạc.',
        empty: 'Không có sản phẩm nào.',
        badge: 'Bộ sưu tập',
        cta: 'Khám phá ngay',
        error: 'Không thể tải bộ sưu tập.',
      },
      hero: {
        initialTitle: 'Nghệ thuật truyền thống Hòa Lạc',
        initialDescription: 'Nơi hội tụ tinh hoa của những đôi bàn tay tài hoa, nơi mỗi đường nét được tạo nên từ ký ức làng nghề và khát vọng đưa bản sắc Việt vươn xa. Chúng tôi trân trọng từng câu chuyện phía sau sản phẩm, để bạn cảm nhận rõ hơi thở truyền thống trong không gian hiện đại.',
        overlayTitle: 'Chào mừng đến với\nWebsite thủ công mỹ nghệ Hòa Lạc',
        cta: 'Khám phá',
        introTitle: 'Từng nhịp thở của làng nghề, từng câu chuyện của người nghệ nhân được dệt nên bằng sự nâng niu và lòng tự hào.',
        introDescription: 'Từ những ngày đầu đặt nền móng, người dân Hòa Lạc đã gìn giữ tinh thần sáng tạo, để mỗi sản phẩm không chỉ là vật dụng mà còn là ký ức của một vùng đất. Những đôi tay tài hoa đã truyền nhau kỹ thuật, hơi thở văn hóa và cả niềm tin rằng nghề truyền thống là sợi dây gắn kết quá khứ với hiện tại.',
        values: {
          heritage: {
            title: 'Nếp Nghề Truyền Lại',
            description: 'Qua từng thế hệ, những bí quyết chế tác được truyền dạy bên bếp lửa ấm. Họ kể cho nhau nghe về nhịp chày, về mùi hương tre phơi nắng và niềm tự hào khi sản phẩm hoàn thiện.',
          },
          culture: {
            title: 'Sắc Màu Văn Hóa',
            description: 'Mỗi họa tiết là một biểu tượng, kể về mùa vụ, tín ngưỡng, nếp sống. Người nghệ nhân chọn màu sắc theo cảm xúc, tạo nên những tác phẩm rực rỡ nhưng hài hòa như chính nhịp sống làng nghề.',
          },
          contemporary: {
            title: 'Hơi Thở Đương Đại',
            description: 'Khi thế giới đổi thay, Hòa Lạc vẫn giữ linh hồn truyền thống nhưng không ngừng cải tiến. Những thiết kế mới mang tính ứng dụng cao, đưa làng nghề tiến gần hơn tới cuộc sống hiện đại.',
          },
        },
        closing: 'Hành trình của chúng tôi là hành trình kể lại những câu chuyện chân thật nhất về con người Hòa Lạc – những người đã chọn gắn bó cả đời với nghề để bảo tồn bản sắc Việt.',
      },
      featured: {
        badge: 'Tinh hoa chọn lọc',
        title: 'Sản phẩm nổi bật',
        description: 'Những tác phẩm thủ công được yêu thích nhất, hội tụ sự tỉ mỉ của người nghệ nhân Hòa Lạc và chất liệu truyền thống.',
        cta: 'Xem cửa hàng',
      },
      contactSection: {
        badge: 'Kết nối với Hòa Lạc',
        title: 'Liên hệ để chạm vào tinh hoa nghề Việt',
        description: 'Chúng tôi luôn sẵn sàng đồng hành cùng bạn trong hành trình khám phá và gìn giữ giá trị thủ công truyền thống.',
        emailPlaceholder: 'Email',
        phonePlaceholder: 'Số điện thoại',
        messagePlaceholder: 'Viết đôi lời cùng chúng tôi',
        cta: 'Liên hệ ngay',
        note: 'Hoặc quý khách có thể kết nối trực tiếp qua các kênh dưới đây',
        hotlineLabel: 'Hotline',
      },
      artisanCraft: {
        badge: 'Hành trình làng nghề',
        title: 'Không gian nghệ nhân Hòa Lạc',
        description: 'Dõi theo nhịp sống của những nghệ nhân, nơi từng đường khắc và nét vẽ đều được nâng niu để giữ trọn tinh hoa truyền thống.',
        slides: {
          first: {
            title: 'Khám phá làng nghề',
            subtitle: 'Tinh hoa thủ công Việt',
            content: 'Mỗi sản phẩm là câu chuyện về bàn tay nghệ nhân, về những giá trị truyền thống được gìn giữ và sáng tạo.',
          },
          second: {
            title: 'Kết nối thợ thủ công',
            subtitle: 'Từ bàn tay đến trái tim',
            content: 'Gặp gỡ những người thợ tài hoa, mang sản phẩm thủ công đến gần hơn với cuộc sống hiện đại.',
          },
          third: {
            title: 'Bảo tồn và phát triển',
            subtitle: 'Di sản sống động',
            content: 'Cùng tiếp sức để làng nghề phát triển bền vững, đưa sản phẩm thủ công Việt vươn xa thế giới.',
          },
        },
        sliderTag: 'Truyền thống & Hiện đại',
      },
      discover: {
        badge: 'Góc truyện làng nghề',
        title: 'Khám phá Hòa Lạc',
        description: 'Những câu chuyện, sự kiện và cảm hứng xoay quanh hành trình gìn giữ và phát triển nghề thủ công truyền thống.',
        cta: 'Xem tất cả bài viết',
        cardTag: 'Khám phá',
      },
    },
    about: {
      breadcrumbHome: 'Trang chủ',
      breadcrumbCurrent: 'Về chúng tôi',
      cloudIntro: {
        description: 'Hòa Lạc – không chỉ là một địa danh, mà còn là nơi hội tụ tinh hoa của những đôi bàn tay tài hoa, nơi mỗi thớ gỗ, sợi tre, hay mảnh gốm đều được thổi hồn, mang theo câu chuyện của người nghệ nhân và văn hóa truyền thống.',
      },
      mission: {
        title: 'Sứ mệnh của chúng tôi',
        items: {
          first: 'Gìn giữ tinh hoa làng nghề Hòa Lạc',
          second: 'Kết nối nghệ nhân với cộng đồng yêu thủ công',
          third: 'Lan tỏa vẻ đẹp văn hóa Việt qua từng sản phẩm',
        },
      },
      whyUs: {
        titleLine1: 'Vì sao lại chọn',
        titleLine2: 'Hoalachandicraft?',
        reasons: {
          first: 'Chân thật & thủ công: Mỗi sản phẩm đều được làm bằng tay, tỉ mỉ trong từng chi tiết, mang hồn cốt của người thợ Việt.',
          second: 'Gắn kết truyền thống & hiện đại: Chúng tôi giữ nguyên nét xưa, nhưng thể hiện theo phong cách gần gũi, phù hợp với đời sống hôm nay.',
          third: 'Sản phẩm mang câu chuyện: Mỗi món đồ không chỉ đẹp mà còn kể về một làng nghề, một con người, một niềm tự hào văn hóa.',
          fourth: 'Bền vững & ý nghĩa: Chúng tôi hướng đến phát triển bền vững, đồng hành cùng nghệ nhân và lan tỏa giá trị thủ công tới cộng đồng.',
        },
      },
    },
    shop: {
      loading: 'Đang tải sản phẩm...',
      empty: 'Không có sản phẩm nào.',
      banner: {
        title: 'Chào mừng đến với website thủ công mỹ nghệ Hòa Lạc',
        subtitle: 'Nơi quy tụ các tác phẩm thủ công tinh xảo',
        cta: 'Khám phá sản phẩm',
      },
      filter: {
        allProductsHeading: 'Tất cả sản phẩm',
        allLabel: 'Tất cả',
        unknownCategory: 'Không tên',
        searchPlaceholder: 'Tìm kiếm sản phẩm...',
        sortButton: 'Sắp xếp',
        sortTitle: 'Sắp xếp theo:',
        scrollLeft: 'Cuộn sang trái',
        scrollRight: 'Cuộn sang phải',
        sort: {
          default: 'Mặc định',
          lowToHigh: 'Giá: thấp đến cao',
          highToLow: 'Giá: cao đến thấp',
          aToZ: 'Tên A -> Z',
          zToA: 'Tên Z -> A',
        },
        searchButton: 'Tìm kiếm',
      },
    },
    blog: {
      breadcrumb: {
        home: 'Trang chủ',
        current: 'Bài viết',
      },
      hero: {
        badge: 'Tin tức làng nghề',
        emptyHighlights: 'Các bài viết sẽ được nổi bật trong thời gian tới.',
        emptyList: 'Chưa có bài viết nào được xuất bản. Vui lòng quay lại sau.',
      },
      featured: {
        badge: 'Bài viết nổi bật',
        title: 'Các bài viết gần đây',
        countLabel: 'Hiển thị {count} trên {total} bài viết',
        readMore: 'Đọc bài viết',
        empty: 'Các câu chuyện mới sẽ sớm được xuất bản.',
      },
      updating: 'Đang cập nhật',
      authorFallback: 'G90 Editorial',
      loadError: 'Không thể tải các bài viết.',
    },
    blogDetail: {
      missing: 'Bài viết không tồn tại.',
      loadError: 'Không thể tải bài viết.',
      backToBlog: 'Quay lại trang blog',
      byLabel: 'Bởi',
      postedIn: 'Đăng ở',
      mainContent: 'Nội dung chính',
      statusLabel: 'Tình trạng',
      idLabel: 'Mã bài viết',
      statusFallback: 'Active',
      categoryFallback: 'Tin tức',
      contentUpdating: 'Nội dung sẽ được cập nhật.',
      relatedBadge: 'Có thể bạn sẽ thích',
      relatedTitle: 'Bài viết liên quan',
      viewAll: 'Xem tất cả',
      relatedSummaryFallback: 'Khám phá thêm về câu chuyện thủ công truyền thống.',
    },
    productCard: {
      fallbackDescription: 'Sản phẩm thủ công mang đậm nét truyền thống',
      sold: '{count} lượt bán',
      rating: '({count})',
      priceLabel: 'Giá bán',
      stock: 'Còn {stock} sản phẩm',
      viewDetail: 'Xem chi tiết',
      addToCart: 'Giỏ hàng',
      buyNow: 'Mua ngay',
      priceSuffix: ' VND',
      soldOut: 'Hết hàng',
    },
    relation: {
      title: 'Sản phẩm tương tự',
      subtitle: 'Khám phá thêm các sản phẩm thủ công tinh xảo',
      loading: 'Đang tải sản phẩm liên quan...',
    },
    contact: {
      title: 'Liên hệ',
      description: 'Đừng ngại gửi cho chúng tôi thông điệp của bạn. Đội ngũ Hòa Lạc Handicraft luôn sẵn sàng lắng nghe.',
      form: {
        name: 'Họ và tên',
        email: 'Email',
        message: 'Nội dung',
        submit: 'Gửi tin nhắn',
      },
      infoTitle: 'Thông tin liên hệ',
      office: 'Văn phòng',
      address: 'Khu Công nghệ cao Hòa Lạc, Thạch Thất, Hà Nội',
      phone: 'Điện thoại',
      emailLabel: 'Email',
      hoursTitle: 'Giờ làm việc',
      hoursValue: 'Thứ 2 - Thứ 6: 8:30 - 17:30',
    },
    policy: {
      title: 'Chính sách',
      updated: 'Cập nhật lần cuối: Tháng 11/2025',
      privacyTitle: 'Chính sách bảo mật',
      privacyContent: 'Chúng tôi cam kết bảo vệ dữ liệu cá nhân của bạn và chỉ sử dụng để cung cấp dịch vụ. Mọi thông tin được mã hóa và lưu trữ an toàn.',
      shippingTitle: 'Chính sách vận chuyển',
      shippingContent: 'Đơn hàng được xử lý trong 24 giờ và giao trong 3-5 ngày làm việc. Chúng tôi hỗ trợ giao hàng toàn quốc qua các đối tác uy tín.',
      returnTitle: 'Chính sách đổi trả',
      returnContent: 'Bạn có thể đổi trả sản phẩm trong vòng 7 ngày kể từ khi nhận hàng nếu sản phẩm bị lỗi hoặc hư hỏng trong quá trình vận chuyển.',
    },
    cart: {
      title: 'Giỏ hàng của bạn',
      empty: 'Giỏ hàng của bạn đang trống.',
      headerProduct: 'Sản phẩm',
      headerQuantity: 'Số lượng',
      headerPrice: 'Giá',
      headerSubtotal: 'Thành tiền',
      summaryTitle: 'Thông tin đơn hàng',
      subtotal: 'Tạm tính',
      shipping: 'Phí vận chuyển',
      total: 'Tổng cộng',
      checkout: 'Tiến hành đặt hàng',
      continueShopping: 'Tiếp tục mua sắm',
      itemsCount: '{count} sản phẩm',
      updating: 'Đang cập nhật...',
      remove: 'Xóa',
      banner: {
        title: 'Giỏ hàng của bạn',
        description: 'Kiểm tra lại sản phẩm trước khi thanh toán để đảm bảo mọi thứ chính xác.',
      },
      emptyInfo: 'Giỏ hàng của bạn đang trống, thêm sản phẩm để tiếp tục nhé!',
      unavailableNotice: 'Sản phẩm đã hết hàng hoặc ngừng kinh doanh.',
      unavailableOnly: 'Giỏ hàng của bạn hiện chỉ chứa các sản phẩm đã hết hàng. Vui lòng xóa chúng trước khi tiếp tục.',
      unavailableConfirm: 'Một số sản phẩm trong giỏ hàng đã hết hàng. Tiếp tục thanh toán với các sản phẩm còn hàng chứ?',
    },
    messages: {
      loginRequired: 'Vui lòng đăng nhập để tiếp tục.',
      loginToAddCart: 'Đăng nhập để thêm vào giỏ hàng.',
      loginToBuyNow: 'Đăng nhập để mua ngay.',
      addedToCart: 'Đã thêm sản phẩm vào giỏ hàng.',
      addedToCartRedirect: 'Đã thêm sản phẩm, đang chuyển tới giỏ hàng...',
      addToCartError: 'Không thể thêm sản phẩm vào giỏ hàng.',
      cartLoadError: 'Không thể tải giỏ hàng.',
      cartUpdateSuccess: 'Đã cập nhật số lượng.',
      cartUpdateError: 'Cập nhật số lượng thất bại.',
      cartRemoveSuccess: 'Đã xóa sản phẩm khỏi giỏ hàng.',
      cartRemoveError: 'Xóa sản phẩm thất bại.',
      checkoutComingSoon: 'Tính năng thanh toán đang được phát triển.',
      cartEmpty: 'Giỏ hàng của bạn đang trống.',
      addressRequired: 'Vui lòng chọn địa chỉ giao hàng.',
      orderSuccess: 'Đặt hàng thành công.',
      orderError: 'Không thể đặt hàng. Vui lòng thử lại.',
      wishlistAdded: 'Đã thêm vào yêu thích.',
      wishlistRemoved: 'Đã xóa khỏi yêu thích.',
      wishlistLoginRequired: 'Đăng nhập để quản lý danh sách yêu thích.',
      removedUnavailable: 'Một số sản phẩm đã hết hàng và được loại khỏi đơn thanh toán.',
      redirectVnpay: 'Đang chuyển hướng đến VNPAY...',
      voucherLoadError: 'Không thể tải danh sách voucher.',
    },
    order: {
      success: 'Đặt hàng thành công',
      details: 'Chi tiết đơn hàng',
      orderId: 'Mã đơn hàng',
      paymentMethod: 'Phương thức thanh toán',
      status: 'Trạng thái',
      codInfo: 'Bạn sẽ thanh toán khi nhận hàng. Vui lòng chuẩn bị tiền mặt hoặc thẻ tín dụng.',
      vnpayInfo: 'Thanh toán đã được xử lý qua VNPAY. Hóa đơn sẽ được gửi đến email của bạn.',
      summary: 'Tóm tắt đơn hàng',
      viewOrders: 'Xem đơn hàng của tôi',
      continueShopping: 'Tiếp tục mua sắm',
      expectedDelivery: 'Thời gian giao hàng dự kiến',
      failed: 'Đặt hàng thất bại',
      retryCheckout: 'Quay lại thanh toán',
      backHome: 'Về trang chủ',
    },
    checkout: {
      title: 'Thanh toán đơn hàng',
      banner: {
        badge: 'Hoa Lac Handicraft',
        title: 'Thanh toán đơn hàng',
        description: 'Kiểm tra địa chỉ, phương thức thanh toán và hoàn tất đơn hàng của bạn một cách an toàn.',
      },
      review: {
        title: 'Kiểm tra đơn hàng',
        empty: 'Không có sản phẩm nào trong giỏ hàng.',
        headers: {
          product: 'Sản phẩm',
          unitPrice: 'Đơn giá',
          quantity: 'Số lượng',
          subtotal: 'Thành tiền',
        },
        productCode: 'Mã hàng',
        artisan: 'Người bán',
      },
      address: {
        title: 'Địa chỉ giao hàng',
        manage: 'Quản lý',
        empty: 'Chưa có địa chỉ giao hàng được lưu.',
        manageCta: 'Quản lý địa chỉ',
        placeholder: 'Chưa chọn địa chỉ',
        defaultBadge: 'Mặc định',
        fallbackName: 'Người nhận',
        fallbackPhone: 'Chưa có số điện thoại',
        fallbackAddress: 'Chưa có địa chỉ chi tiết',
      },
      payment: {
        title: 'Phương thức thanh toán',
        methods: {
          cod: {
            name: 'Thanh toán khi nhận hàng (COD)',
            description: 'Trả tiền mặt khi nhận hàng',
          },
          vnpay: {
            name: 'VNPay',
            description: 'Thanh toán trực tuyến qua VNPay',
          },
        },
      },
      summary: {
        title: 'Đơn hàng của bạn',
        subtotal: 'Tạm tính',
        shipping: 'Phí vận chuyển',
        discount: 'Giảm giá',
        total: 'Tổng cộng',
        voucherLabel: 'Voucher của bạn',
        voucherNone: 'Không sử dụng Voucher',
        voucherPersonal: 'Voucher cá nhân',
        voucherShared: 'Voucher chung',
        voucherEmpty: 'Bạn chưa có Voucher hợp lệ.',
        voucherClear: 'Bỏ chọn Voucher',
        voucherDefault: 'Voucher',
        voucherMin: 'ĐH tối thiểu {amount}',
        voucherMax: 'Giảm tối đa {amount}',
        voucherNotEligible: 'Chưa đạt giá trị tối thiểu.',
        placing: 'Đang đặt hàng...',
        placeOrder: 'Đặt hàng',
        agreement: 'Bằng việc đặt hàng, bạn đồng ý với ',
        agreementLink: 'điều khoản sử dụng',
      },
    },
    auth: {
      common: {
        backLabel: 'Trở về',
        homeLink: 'Trang chủ',
        showPassword: 'Hiện mật khẩu',
        hidePassword: 'Ẩn mật khẩu',
        viLabel: 'Tiếng Việt',
        enLabel: 'English',
      },
      login: {
        heroBadge: 'HoaLacHandicraft',
        heroTitle: 'Chào mừng bạn quay trở lại',
        heroSubtitle: 'Đăng nhập để tiếp tục khám phá những sản phẩm thủ công tinh xảo đến từ Hòa Lạc.',
        welcomeTag: 'Chào mừng trở lại',
        title: 'Đăng nhập',
        subtitle: 'Nhập thông tin bên dưới để tiếp tục trải nghiệm tại HoaLacHandicraft.',
        usernameLabel: 'Tên đăng nhập',
        usernamePlaceholder: 'Tên đăng nhập',
        passwordLabel: 'Mật khẩu',
        passwordPlaceholder: 'Mật khẩu',
        remember: 'Ghi nhớ đăng nhập',
        forgot: 'Quên mật khẩu?',
        submit: 'Đăng nhập',
        submitting: 'Đang đăng nhập...',
        registerPrompt: 'Chưa có tài khoản?',
        registerLink: 'Đăng ký',
        toastSuccess: 'Đăng nhập thành công!',
        toastInvalid: 'Tên đăng nhập hoặc mật khẩu không đúng.',
        toastError: 'Không thể đăng nhập. Vui lòng thử lại.',
        toastInactive: 'Tài khoản đã bị khóa do vi phạm chính sách của website. Vui lòng liên hệ Hoalachandicraft@gmail.com để biết thêm thông tin.',
      },
      register: {
        heroBadge: 'HoaLacHandicraft',
        heroTitle: 'Chào mừng đến với cộng đồng thủ công Việt',
        heroSubtitle: 'Kết nối cùng nghệ nhân Hòa Lạc, khám phá tinh hoa làng nghề và lưu giữ nét đẹp truyền thống.',
        startTag: 'Bắt đầu hành trình',
        title: 'Tạo tài khoản mới',
        subtitle: 'Nhập thông tin dưới đây để gia nhập cộng đồng HoaLacHandicraft.',
        form: {
          emailLabel: 'Email',
          emailPlaceholder: 'Email của bạn',
          usernameLabel: 'Tên đăng nhập',
          usernamePlaceholder: 'Tên đăng nhập của bạn',
          phoneLabel: 'Số điện thoại',
          phonePlaceholder: 'Số điện thoại của bạn',
          displayNameLabel: 'Họ và tên',
          displayNamePlaceholder: 'Họ và tên của bạn',
          dobLabel: 'Ngày sinh',
          dobDay: 'Ngày',
          dobMonth: 'Tháng',
          dobYear: 'Năm',
          passwordLabel: 'Mật khẩu',
          passwordPlaceholder: 'Mật khẩu',
          confirmPasswordLabel: 'Xác nhận mật khẩu',
          confirmPasswordPlaceholder: 'Xác nhận mật khẩu',
        },
        buttons: {
          submit: 'Đăng ký',
          submitting: 'Đang đăng ký...',
        },
        cta: {
          haveAccount: 'Đã có tài khoản?',
          loginLink: 'Đăng nhập',
        },
        otp: {
          title: 'Xác thực OTP',
          description: 'Vui lòng nhập mã xác thực được gửi đến email của bạn',
          notReceived: 'Không nhận được mã?',
          resendReady: 'Gửi lại mã',
          resendCountdown: 'Gửi lại mã ({seconds}s)',
          confirmButton: 'Xác nhận',
          closeAria: 'Đóng cửa sổ',
        },
        toasts: {
          registerSuccess: 'Đăng ký thành công! Vui lòng kiểm tra email để lấy mã OTP.',
          duplicate: 'Email hoặc tên đăng nhập đã tồn tại!',
          registerError: 'Không thể đăng ký. Vui lòng thử lại.',
          waitBeforeResend: 'Vui lòng chờ {seconds}s trước khi gửi lại mã.',
          resendInfo: 'Đang gửi lại mã OTP...',
          resendSuccess: 'Đã gửi lại mã OTP thành công!',
          resendError: 'Không thể gửi lại mã OTP. Vui lòng thử lại sau.',
          otpSuccess: 'Mã OTP đúng, đăng ký thành công! Vui lòng đăng nhập để tiếp tục.',
          otpError: 'Xác thực OTP thất bại.',
        },
        errors: {
          usernameLength: 'Tên đăng nhập phải từ 3–30 ký tự.',
          passwordLength: 'Mật khẩu phải có ít nhất 6 ký tự.',
          passwordMismatch: 'Mật khẩu xác nhận không khớp.',
          emailInvalid: 'Email không hợp lệ.',
          phoneRequired: 'Vui lòng nhập số điện thoại hợp lệ.',
          phoneInvalid: 'Số điện thoại không đúng định dạng. Ví dụ: 0901234567, +84901234567.',
          phoneInvalid84: 'Số điện thoại +84 phải có đầu số 3, 5, 7, 8 hoặc 9 và 8 chữ số tiếp theo.',
          displayNameLength: 'Tên hiển thị không được dài quá 50 ký tự.',
          dobIncomplete: 'Vui lòng chọn đầy đủ Ngày/Tháng/Năm.',
          dobInvalid: 'Ngày sinh không hợp lệ.',
          dobFuture: 'Ngày sinh không thể ở tương lai.',
          dobTooOld: 'Ngày sinh không hợp lệ.',
          dobNonexistent: 'Ngày sinh không tồn tại. Vui lòng chọn lại.',
        },
      },
    },
    general: {
      errorPrefix: 'Lỗi: ',
      unknownError: 'Đã xảy ra lỗi không xác định.',
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      shop: 'Shop',
      blog: 'Blog',
      contact: 'Contact',
      policy: 'Policies',
    },
    header: {
      searchPlaceholder: 'Search...',
      login: 'Sign in',
      profile: 'My account',
      orders: 'Orders',
      logout: 'Sign out',
      notificationsEmpty: 'No new notifications.',
      cartTooltip: 'Cart',
    },
    home: {
      collections: {
        title: 'Product collections',
        description: 'Explore curated collections where every design captures the spirit of Hoa Lac craftsmanship.',
        empty: 'No products available.',
        badge: 'Collections',
        cta: 'Discover now',
        error: 'Unable to load collections.',
      },
      hero: {
        initialTitle: 'Hoa Lac traditional artistry',
        initialDescription: 'Where masterful hands meet treasured memories of the craft village. Every detail carries the desire to share Vietnamese identity with the world. We cherish the stories behind each piece so you can feel tradition breathing within modern spaces.',
        overlayTitle: 'Welcome to the\nHoa Lac Handicraft website',
        cta: 'Explore',
        introTitle: 'Every heartbeat of the craft village and every artisan story is woven with care and pride.',
        introDescription: 'From the early days of the village, the people of Hoa Lac have preserved their creative spirit so every creation is more than an object—it carries the memory of its homeland. Generations of artisans pass down techniques, cultural breath, and the belief that tradition ties the past to the present.',
        values: {
          heritage: {
            title: 'Craft legacy preserved',
            description: 'Across generations, crafting secrets are shared by the warm hearth. They celebrate the rhythm of tools, the scent of sun-dried bamboo, and the pride of a finished piece.',
          },
          culture: {
            title: 'Cultural colors',
            description: 'Each motif is a symbol of seasons, beliefs, and way of life. Artisans choose colors by feeling, creating vibrant yet harmonious works that mirror village rhythms.',
          },
          contemporary: {
            title: 'Contemporary breath',
            description: 'While the world changes, Hoa Lac keeps its soul yet constantly innovates. New designs focus on usability, bringing traditional craft closer to modern living.',
          },
        },
        closing: 'Our journey is to tell the most sincere stories about the people of Hoa Lac—those who devote their lives to preserving Vietnamese identity through their craft.',
      },
      featured: {
        badge: 'Curated highlights',
        title: 'Featured products',
        description: 'Beloved handcrafted pieces that showcase meticulous Hoa Lac artistry paired with time-honored materials.',
        cta: 'Visit the shop',
      },
      contactSection: {
        badge: 'Connect with Hoa Lac',
        title: 'Contact Us',
        description: 'We are ready to accompany you on the journey of exploring and preserving traditional craft values.',
        emailPlaceholder: 'Email',
        phonePlaceholder: 'Phone number',
        messagePlaceholder: 'Share a message with us',
        cta: 'Contact us',
        note: 'Or reach us directly through the channels below',
        hotlineLabel: 'Hotline',
      },
      artisanCraft: {
        badge: 'Craft village journey',
        title: 'Hoa Lac artisan space',
        description: 'Follow the rhythm of artisan life, where every carving and brushstroke is cherished to preserve traditional essence.',
        slides: {
          first: {
            title: 'Discover the craft village',
            subtitle: 'Vietnamese craftsmanship',
            content: 'Each piece tells a story of artisan hands and the traditional values they preserve and innovate.',
          },
          second: {
            title: 'Connect with artisans',
            subtitle: 'From hands to hearts',
            content: 'Meet talented makers who bring handcrafted creations closer to everyday life.',
          },
          third: {
            title: 'Preserve and grow',
            subtitle: 'A living heritage',
            content: 'Join the effort to sustain the craft village and share Vietnamese handcraft with the world.',
          },
        },
        sliderTag: 'Tradition & Modernity',
      },
      discover: {
        badge: 'Craft village stories',
        title: 'Discover Hoa Lac',
        description: 'Stories, events, and inspirations from the journey of preserving and elevating traditional craftsmanship.',
        cta: 'View all articles',
        cardTag: 'Discover',
      },
    },
    about: {
      breadcrumbHome: 'Home',
      breadcrumbCurrent: 'About Us',
      cloudIntro: {
        description: 'Hoa Lac is more than a place—it is a gathering of masterful hands where every wood grain, bamboo fiber, and ceramic shard carries the spirit of its artisans and their cultural heritage.',
      },
      mission: {
        title: 'Our mission',
        items: {
          first: 'Preserve the heritage of the Hoa Lac craft village',
          second: 'Connect artisans with the community that loves handcrafts',
          third: 'Share the beauty of Vietnamese culture through every creation',
        },
      },
      whyUs: {
        titleLine1: 'Why choose',
        titleLine2: 'Hoalachandicraft?',
        reasons: {
          first: 'Authentic & handcrafted: Every piece is meticulously handmade, carrying the soul of Vietnamese artisans.',
          second: 'Bridging tradition & modern life: We honor timeless designs while adapting them for today’s living spaces.',
          third: 'Stories behind each piece: Every item reflects a craft village, a dedicated artisan, and a cultural pride.',
          fourth: 'Meaningful & sustainable: We champion sustainable growth, stand beside artisans, and spread craft values to the community.',
        },
      },
    },
    shop: {
      loading: 'Loading products...',
      empty: 'No products available.',
      banner: {
        title: 'Welcome to the Hoa Lac Handicraft boutique',
        subtitle: 'A curated collection of refined handcrafted pieces',
        cta: 'Discover products',
      },
      filter: {
        allProductsHeading: 'All products',
        allLabel: 'All',
        unknownCategory: 'Untitled',
        searchPlaceholder: 'Search products...',
        sortButton: 'Sort',
        sortTitle: 'Sort by:',
        scrollLeft: 'Scroll left',
        scrollRight: 'Scroll right',
        sort: {
          default: 'Default',
          lowToHigh: 'Price: low to high',
          highToLow: 'Price: high to low',
          aToZ: 'Name A -> Z',
          zToA: 'Name Z -> A',
        },
        searchButton: 'Search',
      },
    },
    blog: {
      breadcrumb: {
        home: 'Home',
        current: 'Blog',
      },
      hero: {
        badge: 'Craft village news',
        emptyHighlights: 'Featured stories will appear here soon.',
        emptyList: 'No articles have been published yet. Please check back later.',
      },
      featured: {
        badge: 'Featured posts',
        title: 'Recent articles',
        countLabel: 'Showing {count} of {total} articles',
        readMore: 'Read article',
        empty: 'More stories will be published soon.',
      },
      updating: 'Updating',
      authorFallback: 'G90 Editorial',
      loadError: 'Unable to load articles.',
    },
    blogDetail: {
      missing: 'The article does not exist.',
      loadError: 'Unable to load the article.',
      backToBlog: 'Back to blog',
      byLabel: 'By',
      postedIn: 'Posted in',
      mainContent: 'Main content',
      statusLabel: 'Status',
      idLabel: 'Article ID',
      statusFallback: 'Active',
      categoryFallback: 'News',
      contentUpdating: 'Content will be updated soon.',
      relatedBadge: 'You may also like',
      relatedTitle: 'Related articles',
      viewAll: 'View all',
      relatedSummaryFallback: 'Discover more about traditional craftsmanship stories.',
    },
    productCard: {
      fallbackDescription: 'Handcrafted piece inspired by tradition',
      sold: '{count} sold',
      rating: '({count})',
      priceLabel: 'Price',
      stock: '{stock} items left',
      viewDetail: 'View detail',
      addToCart: 'Add to cart',
      buyNow: 'Buy now',
      priceSuffix: ' VND',
      soldOut: 'Sold out',
    },
    relation: {
      title: 'Similar products',
      subtitle: 'Explore more refined handcrafted creations',
      loading: 'Loading related products...',
    },
    contact: {
      title: 'Contact',
      description: 'Feel free to drop us a message. The Hoa Lac Handicraft team is ready to listen and support you.',
      form: {
        name: 'Full name',
        email: 'Email',
        message: 'Message',
        submit: 'Send message',
      },
      infoTitle: 'Contact information',
      office: 'Office',
      address: 'Hoa Lac Hi-Tech Park, Thach That, Ha Noi',
      phone: 'Phone',
      emailLabel: 'Email',
      hoursTitle: 'Working hours',
      hoursValue: 'Monday - Friday: 8:30 AM - 5:30 PM',
    },
    policy: {
      title: 'Policies',
      updated: 'Last updated: November 2025',
      privacyTitle: 'Privacy policy',
      privacyContent: 'We are committed to protecting your personal data and only use it to deliver our services. All information is encrypted and stored securely.',
      shippingTitle: 'Shipping policy',
      shippingContent: 'Orders are processed within 24 hours and delivered within 3-5 business days nationwide via trusted partners.',
      returnTitle: 'Return policy',
      returnContent: 'You can return products within 7 days of delivery if they are defective or damaged during transportation.',
    },
    cart: {
      title: 'Your cart',
      empty: 'Your cart is empty.',
      headerProduct: 'Product',
      headerQuantity: 'Quantity',
      headerPrice: 'Unit price',
      headerSubtotal: 'Subtotal',
      summaryTitle: 'Order summary',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      total: 'Total',
      checkout: 'Proceed to checkout',
      continueShopping: 'Continue shopping',
      itemsCount: '{count} items',
      updating: 'Updating...',
      remove: 'Remove',
      banner: {
        title: 'Your cart',
        description: 'Review your items before checkout to make sure everything looks right.',
      },
      emptyInfo: 'Your cart is empty—add some handmade treasures to continue!',
      unavailableNotice: 'This item is out of stock or no longer available.',
      unavailableOnly: 'Your cart currently contains only out-of-stock items. Please remove them before continuing.',
      unavailableConfirm: 'Some items in your cart are out of stock. Continue to checkout with the remaining items?',
    },
    messages: {
      loginRequired: 'Please log in to continue.',
      loginToAddCart: 'Sign in to add items to your cart.',
      loginToBuyNow: 'Sign in to buy now.',
      addedToCart: 'Product added to cart.',
      addedToCartRedirect: 'Product added. Redirecting to cart...',
      addToCartError: 'Could not add the product to cart.',
      cartLoadError: 'Unable to load your cart.',
      cartUpdateSuccess: 'Quantity updated.',
      cartUpdateError: 'Failed to update quantity.',
      cartRemoveSuccess: 'Item removed from cart.',
      cartRemoveError: 'Failed to remove item.',
      checkoutComingSoon: 'Checkout is coming soon.',
      cartEmpty: 'Your cart is empty.',
      addressRequired: 'Please select a shipping address.',
      orderSuccess: 'Order placed successfully.',
      orderError: 'Could not place the order. Please try again.',
      wishlistAdded: 'Added to your wishlist.',
      wishlistRemoved: 'Removed from your wishlist.',
      wishlistLoginRequired: 'Sign in to manage your wishlist.',
      removedUnavailable: 'Some items were out of stock and removed from checkout.',
      redirectVnpay: 'Redirecting to VNPAY...',
      voucherLoadError: 'Unable to load vouchers.',
    },
    order: {
      success: 'Order Placed Successfully',
      details: 'Order Details',
      orderId: 'Order ID',
      paymentMethod: 'Payment Method',
      status: 'Status',
      codInfo: 'You will pay when receiving your order. Please prepare cash or credit card.',
      vnpayInfo: 'Payment has been processed through VNPAY. An invoice will be sent to your email.',
      summary: 'Order Summary',
      viewOrders: 'View My Orders',
      continueShopping: 'Continue Shopping',
      expectedDelivery: 'Expected Delivery Time',
      failed: 'Order Failed',
      retryCheckout: 'Return to Checkout',
      backHome: 'Back to Home',
    },
    checkout: {
      title: 'Checkout',
      banner: {
        badge: 'Hoa Lac Handicraft',
        title: 'Complete your order',
        description: 'Review your address, payment method, and finalize your order confidently.',
      },
      review: {
        title: 'Order review',
        empty: 'There are no items in your cart.',
        headers: {
          product: 'Product',
          unitPrice: 'Unit price',
          quantity: 'Quantity',
          subtotal: 'Subtotal',
        },
        productCode: 'SKU',
        artisan: 'Seller',
      },
      address: {
        title: 'Shipping address',
        manage: 'Manage',
        empty: 'No saved shipping addresses yet.',
        manageCta: 'Manage addresses',
        placeholder: 'No address selected',
        defaultBadge: 'Default',
        fallbackName: 'Recipient',
        fallbackPhone: 'Phone number unavailable',
        fallbackAddress: 'No detailed address provided',
      },
      payment: {
        title: 'Payment method',
        methods: {
          cod: {
            name: 'Cash on delivery (COD)',
            description: 'Pay in cash when the order arrives',
          },
          vnpay: {
            name: 'VNPay',
            description: 'Secure online payment via VNPay',
          },
        },
      },
      summary: {
        title: 'Your order',
        subtotal: 'Subtotal',
        shipping: 'Shipping fee',
        discount: 'Discount',
        total: 'Total',
        voucherLabel: 'Your vouchers',
        voucherNone: 'Do not use a voucher',
        voucherPersonal: 'Personal vouchers',
        voucherShared: 'Shared vouchers',
        voucherEmpty: 'No eligible vouchers available.',
        voucherClear: 'Remove voucher',
        voucherDefault: 'Voucher',
        voucherMin: 'Min order {amount}',
        voucherMax: 'Max discount {amount}',
        voucherNotEligible: 'Minimum order value not reached.',
        placing: 'Placing order...',
        placeOrder: 'Place order',
        agreement: 'By placing the order, you agree to ',
        agreementLink: 'the terms of use',
      },
    },
    auth: {
      common: {
        backLabel: 'Back',
        homeLink: 'Home',
        showPassword: 'Show password',
        hidePassword: 'Hide password',
        viLabel: 'Vietnamese',
        enLabel: 'English',
      },
      login: {
        heroBadge: 'HoaLacHandicraft',
        heroTitle: 'Welcome back',
        heroSubtitle: 'Sign in to keep exploring the handcrafted creations from Hoa Lac.',
        welcomeTag: 'Welcome back',
        title: 'Sign in',
        subtitle: 'Enter your credentials below to continue your experience at HoaLacHandicraft.',
        usernameLabel: 'Username',
        usernamePlaceholder: 'Username',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Password',
        remember: 'Remember me',
        forgot: 'Forgot password?',
        submit: 'Sign in',
        submitting: 'Signing in...',
        registerPrompt: 'Don’t have an account?',
        registerLink: 'Sign up',
        toastSuccess: 'Signed in successfully!',
        toastInvalid: 'Incorrect username or password.',
        toastError: 'Unable to sign in. Please try again.',
        toastInactive: 'Your account has been locked for violating our policies. Please contact Hoalachandicraft@gmail.com for more information.',
      },
      register: {
        heroBadge: 'HoaLacHandicraft',
        heroTitle: 'Welcome to the Vietnamese craft community',
        heroSubtitle: 'Connect with Hoa Lac artisans, discover traditional craftsmanship, and preserve cultural values.',
        startTag: 'Begin your journey',
        title: 'Create a new account',
        subtitle: 'Fill in the information below to join the HoaLacHandicraft community.',
        form: {
          emailLabel: 'Email',
          emailPlaceholder: 'Your email',
          usernameLabel: 'Username',
          usernamePlaceholder: 'Your username',
          phoneLabel: 'Phone number',
          phonePlaceholder: 'Your phone number',
          displayNameLabel: 'Full name',
          displayNamePlaceholder: 'Your full name',
          dobLabel: 'Date of birth',
          dobDay: 'Day',
          dobMonth: 'Month',
          dobYear: 'Year',
          passwordLabel: 'Password',
          passwordPlaceholder: 'Password',
          confirmPasswordLabel: 'Confirm password',
          confirmPasswordPlaceholder: 'Confirm password',
        },
        buttons: {
          submit: 'Sign up',
          submitting: 'Signing up...',
        },
        cta: {
          haveAccount: 'Already have an account?',
          loginLink: 'Sign in',
        },
        otp: {
          title: 'OTP verification',
          description: 'Enter the verification code sent to your email.',
          notReceived: 'Didn’t receive the code?',
          resendReady: 'Resend code',
          resendCountdown: 'Resend code ({seconds}s)',
          confirmButton: 'Confirm',
          closeAria: 'Close dialog',
        },
        toasts: {
          registerSuccess: 'Registration successful! Please check your email for the OTP code.',
          duplicate: 'Email or username already exists!',
          registerError: 'Unable to register. Please try again.',
          waitBeforeResend: 'Please wait {seconds}s before requesting a new code.',
          resendInfo: 'Sending the OTP again...',
          resendSuccess: 'OTP resent successfully!',
          resendError: 'Unable to resend the OTP. Please try again later.',
          otpSuccess: 'OTP verified successfully! Please sign in to continue.',
          otpError: 'OTP verification failed.',
        },
        errors: {
          usernameLength: 'Username must be between 3 and 30 characters.',
          passwordLength: 'Password must be at least 6 characters.',
          passwordMismatch: 'Password confirmation does not match.',
          emailInvalid: 'Invalid email address.',
          phoneRequired: 'Please enter a valid phone number.',
          phoneInvalid: 'Phone number format is invalid. Examples: 0901234567, +84901234567.',
          phoneInvalid84: 'Phone numbers starting with +84 must use 3, 5, 7, 8, or 9 and include 8 following digits.',
          displayNameLength: 'Display name cannot exceed 50 characters.',
          dobIncomplete: 'Please select the full day, month, and year.',
          dobInvalid: 'Invalid date of birth.',
          dobFuture: 'Date of birth cannot be in the future.',
          dobTooOld: 'Invalid date of birth.',
          dobNonexistent: 'The selected date of birth does not exist. Please try again.',
        },
      },
    },
    general: {
      errorPrefix: 'Error: ',
      unknownError: 'An unknown error occurred.',
    },
  },
};

export const LanguageContext = createContext({
  language: 'vi',
  changeLanguage: () => {},
  t: (key) => key,
});

const getStoredLanguage = () => {
  if (typeof window === 'undefined') return 'vi';
  return localStorage.getItem('app_language') || 'vi';
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getStoredLanguage);

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
  }, []);

  const translate = useCallback(
    (key, replacements = {}) => {
      if (!key) return '';

      const rawValue = key
        .split('.')
        .reduce((acc, part) => {
          if (acc && typeof acc === 'object') {
            return acc[part];
          }
          return undefined;
        }, translations[language]);

      if (typeof rawValue !== 'string') {
        return key;
      }

      return Object.keys(replacements).reduce(
        (acc, placeholder) => acc.replace(`{${placeholder}}`, replacements[placeholder]),
        rawValue,
      );
    },
    [language],
  );

  const value = useMemo(
    () => ({
      language,
      changeLanguage,
      t: translate,
    }),
    [language, changeLanguage, translate],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

LanguageProvider.propTypes = {
  children: PropTypes.node.isRequired,
};
