using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Threading;
using AutoMapper;
using Backend_SEP490.Constants;
using Backend_SEP490.Data;
using Backend_SEP490.DTOs.Request;
using Backend_SEP490.DTOs.Response;
using Backend_SEP490.Models;
using Backend_SEP490.Repositories;

namespace Backend_SEP490.Services.impl
{
    public class VoucherServiceImpl : GenericServices, IVoucherService
    {
        private static readonly TimeSpan RefundVoucherValidity = TimeSpan.FromDays(365 * 5);
        private static readonly TimeSpan FestivalReminderWindow = TimeSpan.FromDays(1);
        private static readonly TimeSpan LoyaltyAgeThreshold = TimeSpan.FromDays(730);
        private const decimal LargeOrderThreshold = 5_000_000m;
        private const decimal LargeOrderDiscountPercent = 5m;
        private readonly INotificationService _notificationService;

        public VoucherServiceImpl(
            IMapper mapper,
            IUnitOfWork unitOfWork,
            INotificationService notificationService) : base(mapper, unitOfWork)
        {
            _notificationService = notificationService;
        }

        public async Task<ResponseUserVoucherCollection> GetVoucherByUserIdAsync(string userId)
        {
            if (string.IsNullOrWhiteSpace(userId))
            {
                return new ResponseUserVoucherCollection();
            }

            var now = DateTime.UtcNow;
            var shared = await _context.Voucher.GetActiveSharedVouchersAsync(now);
            var personal = await _context.Voucher.GetActivePersonalVouchersAsync(userId, now);

            return new ResponseUserVoucherCollection
            {
                Shared = _mapper.Map<IEnumerable<ResponseDTOVoucher>>(shared),
                Personal = _mapper.Map<IEnumerable<ResponseDTOVoucher>>(personal)
            };
        }

        public async Task<string> CreateVoucherAsync(string userId, RequestCreateVoucher request)
        {
            if (request == null)
            {
                return "Invalid voucher payload!";
            }

            var existing = await _context.Voucher.GetVoucherByCodeAsync(request.Code);
            if (existing != null)
            {
                return "Voucher code already exists!";
            }

            var voucher = new Voucher
            {
                Code = request.Code,
                Description = request.Description,
                DiscountType = request.DiscountType,
                DiscountValue = request.DiscountValue,
                MinOrderAmount = request.MinOrderAmount,
                MaxDiscountAmount = request.MaxDiscountAmount,
                StartDate = NormalizeUtc(request.StartDate),
                EndDate = NormalizeUtc(request.EndDate),
                UsageLimit = request.UsageLimit,
                UsedCount = 0,
                IsActive = request.IsActive,
                IsShared = request.IsShared,
                OwnerUserId = request.OwnerUserId,
                SingleUse = request.SingleUse,
                Source = request.Source,
                IsAutoGenerated = false,
                CreatedDate = DateTime.UtcNow,
                AssignedAt = string.IsNullOrWhiteSpace(request.OwnerUserId) ? null : DateTime.UtcNow,
                CreatedById = userId,
                UpdatedDate = DateTime.UtcNow
            };

            var status = await _context.Voucher.CreateVoucherAsync(voucher);
            if (status.Contains("success", StringComparison.OrdinalIgnoreCase))
            {
                if (!voucher.IsShared && !string.IsNullOrWhiteSpace(voucher.OwnerUserId))
                {
                    await _notificationService.NotifyVoucherGrantedAsync(
                        voucher.OwnerUserId,
                        voucher,
                        "Ban vua duoc tang voucher rieng. Hay dung cho lan mua tiep theo nhe!");
                }
                else
                {
                    await _notificationService.NotifyPromotionAsync(voucher);
                }
            }

            return status;
        }

        public async Task<string> DeleteVoucherAsync(int voucherId)
        {
            var voucher = await _context.Voucher.GetVoucherByIdAsync(voucherId);
            if (voucher == null)
            {
                return "Voucher not found!";
            }

            return await _context.Voucher.DeleteVoucherAsync(voucher);
        }

        public async Task<PagedResult<ResponseDTOVoucher>> GetAllVoucherAsync(int pageIndex, int pageSize)
        {
            var vouchers = await _context.Voucher.GetAllVoucherAsync();
            var totalCount = vouchers.Count;
            var paged = vouchers.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();

            return new PagedResult<ResponseDTOVoucher>
            {
                Items = _mapper.Map<List<ResponseDTOVoucher>>(paged),
                TotalCount = totalCount,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
        }

        public async Task<ResponseDTOVoucher> GetVoucherByIdAsync(int voucherId)
        {
            var voucher = await _context.Voucher.GetVoucherByIdAsync(voucherId);
            return _mapper.Map<ResponseDTOVoucher>(voucher);
        }

        public async Task<string> UpdateVoucherAsync(int voucherId, RequestUpdateVoucher request)
        {
            var voucher = await _context.Voucher.GetVoucherByIdAsync(voucherId);
            if (voucher == null)
            {
                return "Voucher not found!";
            }

            return await _context.Voucher.UpdateVoucherAsync(voucher, request);
        }

        public async Task<Voucher?> CreateRefundVoucherAsync(string userId, Order order, decimal refundAmount, string? reason)
        {
            if (string.IsNullOrWhiteSpace(userId) || order == null || refundAmount <= 0)
            {
                return null;
            }

            var request = new VoucherIssueRequest
            {
                OwnerUserId = userId,
                DiscountType = "Fixed",
                DiscountValue = refundAmount,
                StartDateUtc = DateTime.UtcNow,
                EndDateUtc = DateTime.UtcNow.Add(RefundVoucherValidity),
                UsageLimit = 1,
                IsShared = false,
                SingleUse = true,
                IsAutoGenerated = true,
                Source = VoucherSources.ForRefund(order.OrderNumber ?? order.Id ?? Guid.NewGuid().ToString("N")),
                Description = $"Hoan tien cho don {order.OrderNumber}",
                NotificationMessage = $"Huy don thanh cong. Ban nhan duoc voucher {refundAmount:N0} VND cho lan mua tiep.",
                CodePrefix = "RFND"
            };

            if (!string.IsNullOrWhiteSpace(reason))
            {
                request.Description += $" - {reason}";
            }

            return await IssueVoucherAsync(request, CancellationToken.None);
        }

        public async Task<Voucher?> TryGrantLargeOrderVoucherAsync(Order order)
        {
            if (order == null ||
                order.TotalAmount < LargeOrderThreshold ||
                string.IsNullOrWhiteSpace(order.CustomerId))
            {
                return null;
            }

            var source = VoucherSources.ForLargeOrder(order.OrderNumber ?? order.Id ?? Guid.NewGuid().ToString("N"));
            var existing = await _context.Voucher.GetBySourceAsync(source);
            if (existing != null)
            {
                return existing;
            }

            var request = new VoucherIssueRequest
            {
                OwnerUserId = order.CustomerId,
                DiscountType = "Percent",
                DiscountValue = LargeOrderDiscountPercent,
                MinOrderAmount = order.TotalAmount * 0.5m,
                StartDateUtc = DateTime.UtcNow,
                EndDateUtc = DateTime.UtcNow.AddMonths(2),
                UsageLimit = 1,
                IsShared = false,
                SingleUse = true,
                IsAutoGenerated = true,
                Source = source,
                Description = "Qua tang cho don hang gia tri lon",
                NotificationMessage = "Cam on ban! Don hang lon vua qua duoc tang voucher giam 5% cho lan mua tiep.",
                CodePrefix = "VIP"
            };

            return await IssueVoucherAsync(request, CancellationToken.None);
        }

        public async Task RunAutomationJobsAsync(CancellationToken cancellationToken)
        {
            var now = DateTime.UtcNow;
            await EnsureFestivalVouchersAsync(now.Year, cancellationToken);
            await EnsureLoyaltyVouchersAsync(now, cancellationToken);
            await SendFestivalExpiryRemindersAsync(now, cancellationToken);
        }

        private async Task<Voucher?> IssueVoucherAsync(VoucherIssueRequest request, CancellationToken cancellationToken)
        {
            var code = await GenerateVoucherCodeAsync(request.CodePrefix ?? "VC", cancellationToken);
            var voucher = new Voucher
            {
                Code = code,
                Description = request.Description,
                DiscountType = request.DiscountType,
                DiscountValue = request.DiscountValue,
                MinOrderAmount = request.MinOrderAmount,
                MaxDiscountAmount = request.MaxDiscountAmount,
                StartDate = NormalizeUtc(request.StartDateUtc),
                EndDate = NormalizeUtc(request.EndDateUtc),
                UsageLimit = request.UsageLimit,
                UsedCount = 0,
                IsActive = true,
                IsShared = request.IsShared,
                OwnerUserId = request.OwnerUserId,
                SingleUse = request.SingleUse,
                IsAutoGenerated = request.IsAutoGenerated,
                Source = request.Source,
                CreatedDate = DateTime.UtcNow,
                AssignedAt = string.IsNullOrWhiteSpace(request.OwnerUserId) ? null : DateTime.UtcNow,
                CreatedById = request.CreatorUserId ?? "SYSTEM",
                UpdatedDate = DateTime.UtcNow
            };

            var status = await _context.Voucher.CreateVoucherAsync(voucher);
            if (!status.Contains("success", StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            if (!string.IsNullOrWhiteSpace(voucher.OwnerUserId))
            {
                await _notificationService.NotifyVoucherGrantedAsync(
                    voucher.OwnerUserId,
                    voucher,
                    request.NotificationMessage);
            }
            else if (voucher.IsShared)
            {
                await _notificationService.NotifyPromotionAsync(voucher);
            }

            return voucher;
        }

        private async Task<string> GenerateVoucherCodeAsync(string prefix, CancellationToken cancellationToken)
        {
            var normalized = string.IsNullOrWhiteSpace(prefix)
                ? "VC"
                : new string(prefix.Where(char.IsLetterOrDigit).ToArray()).ToUpperInvariant();

            if (string.IsNullOrWhiteSpace(normalized))
            {
                normalized = "VC";
            }

            for (var attempt = 0; attempt < 10; attempt++)
            {
                var randomValue = RandomNumberGenerator.GetInt32(100000, 999999);
                var candidate = $"{normalized}-{randomValue}";
                var existing = await _context.Voucher.GetVoucherByCodeAsync(candidate);
                if (existing == null)
                {
                    return candidate;
                }

                if (cancellationToken.IsCancellationRequested)
                {
                    break;
                }
            }

            return $"{normalized}-{Guid.NewGuid():N}".Substring(0, Math.Min(20, normalized.Length + 13));
        }

        private async Task EnsureFestivalVouchersAsync(int year, CancellationToken cancellationToken)
        {
            foreach (var festival in VietnameseHolidayDefinitions.Festivals)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    break;
                }

                var source = VoucherSources.ForFestival(festival.Code, year);
                var existing = await _context.Voucher.GetBySourceAsync(source);
                if (existing != null)
                {
                    continue;
                }

                var (start, end) = festival.RangeResolver(year);
                var request = new VoucherIssueRequest
                {
                    DiscountType = "Percent",
                    DiscountValue = festival.DiscountPercent,
                    StartDateUtc = start,
                    EndDateUtc = end,
                    UsageLimit = festival.UsageLimit,
                    IsShared = true,
                    SingleUse = false,
                    IsAutoGenerated = true,
                    Source = source,
                    Description = festival.Name,
                    CodePrefix = festival.Code
                };

                await IssueVoucherAsync(request, cancellationToken);
            }
        }

        private async Task EnsureLoyaltyVouchersAsync(DateTime now, CancellationToken cancellationToken)
        {
            var users = await _context.Users.GetActiveUsersAsync();
            if (users == null || users.Count == 0)
            {
                return;
            }

            var prefix = VoucherSources.LoyaltyPrefix(now.Year);
            var existingSources = await _context.Voucher.GetSourcesByPrefixAsync(prefix);
            var existingSet = new HashSet<string>(existingSources, StringComparer.OrdinalIgnoreCase);

            foreach (var user in users)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    break;
                }

                if (user?.UserID == null || !user.CreateAt.HasValue)
                {
                    continue;
                }

                var createdAtUtc = user.CreateAt.Value.Kind == DateTimeKind.Utc
                    ? user.CreateAt.Value
                    : DateTime.SpecifyKind(user.CreateAt.Value, DateTimeKind.Utc);

                if (now - createdAtUtc < LoyaltyAgeThreshold)
                {
                    continue;
                }

                var source = VoucherSources.ForLoyalty(user.UserID, now.Year);
                if (existingSet.Contains(source))
                {
                    continue;
                }

                var request = new VoucherIssueRequest
                {
                    OwnerUserId = user.UserID,
                    DiscountType = "Percent",
                    DiscountValue = 7m,
                    MinOrderAmount = 200000m,
                    StartDateUtc = now,
                    EndDateUtc = now.AddMonths(3),
                    UsageLimit = 1,
                    IsShared = false,
                    SingleUse = true,
                    IsAutoGenerated = true,
                    Source = source,
                    Description = "Qua tang danh cho khach hang gan bo lau nam",
                    NotificationMessage = "Ban nhan qua tang trung thanh! Dung voucher de duoc giam gia nhe.",
                    CodePrefix = "LOYAL"
                };

                var voucher = await IssueVoucherAsync(request, cancellationToken);
                if (voucher != null)
                {
                    existingSet.Add(source);
                }
            }
        }

        private async Task SendFestivalExpiryRemindersAsync(DateTime now, CancellationToken cancellationToken)
        {
            var expiring = await _context.Voucher.GetExpiringSharedVouchersAsync(now, now.Add(FestivalReminderWindow));
            if (expiring == null || expiring.Count == 0)
            {
                return;
            }

            var users = await _context.Users.GetActiveUsersAsync();
            var userIds = users?
                .Where(u => !string.IsNullOrWhiteSpace(u.UserID))
                .Select(u => u.UserID!)
                .ToList();

            if (userIds == null || userIds.Count == 0)
            {
                return;
            }

            foreach (var voucher in expiring)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    break;
                }

                if (voucher.LastReminderAt.HasValue &&
                    (now - voucher.LastReminderAt.Value).TotalHours < 12)
                {
                    continue;
                }

                await _notificationService.NotifyVoucherEventExpiringAsync(voucher, userIds);
                voucher.LastReminderAt = now;
            }

            await _context.SaveChangesAsync();
        }

        private static DateTime NormalizeUtc(DateTime value)
        {
            return value.Kind == DateTimeKind.Utc
                ? value
                : DateTime.SpecifyKind(value, DateTimeKind.Utc);
        }
    }
}
