using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend_SEP490.DTOs.Response
{
    public class ResponseDTOVoucher
    {
        public int VoucherId { get; set; }
        public string Code { get; set; }
        public string? Description { get; set; }
        public string DiscountType { get; set; } // "Percent" or "Fixed"
        public decimal DiscountValue { get; set; }
        public decimal? MinOrderAmount { get; set; }
        public decimal? MaxDiscountAmount { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int? UsageLimit { get; set; }
        public int UsedCount { get; set; } = 0;
        public bool IsActive { get; set; } = true;
        public bool IsShared { get; set; } = true;
        public bool IsAutoGenerated { get; set; }
        public bool SingleUse { get; set; }
        public string? OwnerUserId { get; set; }
        public string? Source { get; set; }
        public DateTime? AssignedAt { get; set; }
        public DateTime? LastReminderAt { get; set; }
        public DateTime CreatedDate { get; set; }
        public string? CreatedById { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}
