import React, {
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react';
import {
  FaPlus,
  FaEdit,
  FaTrash,
  FaSync,
  FaEye,
  FaSpinner,
} from 'react-icons/fa';
import { toast } from 'react-toastify';
import Pagination from '../shared/Pagination';
import { VoucherService } from '../../services/modules/voucher/voucherService';
import { UserService } from '../../services/modules/users/userService';

const DEFAULT_PAGE_SIZE = 10;
const PAGE_SIZE_OPTIONS = [5, 10, 20];

const emptyForm = {
  code: '',
  description: '',
  discountType: 'Percent',
  discountValue: 0,
  minOrderAmount: '',
  maxDiscountAmount: '',
  startDate: '',
  endDate: '',
  usageLimit: 1,
  usedCount: 0,
  isActive: true,
  isShared: true,
  singleUse: false,
  ownerUserId: '',
  source: '',
};

const numberOrZero = (val) => {
  const num = Number(val);
  return Number.isNaN(num) ? 0 : num;
};

const formatCurrency = (value) => new Intl.NumberFormat('vi-VN', {
  style: 'currency',
  currency: 'VND',
  minimumFractionDigits: 0,
}).format(numberOrZero(value));

const formatDateTime = (value) => {
  if (!value) return '--';
  const d = new Date(value);
  return Number.isNaN(d.getTime())
    ? value
    : d.toLocaleString('vi-VN', { hour12: false });
};

const formatAmountOrDash = (value) => {
  if (value === null || value === undefined || value === '') return '--';
  return formatCurrency(value);
};

const toInputDateTime = (value) => {
  if (!value) return '';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return '';
  const iso = d.toISOString();
  return iso.substring(0, 16);
};

const VoucherManagement = () => {
  const [vouchers, setVouchers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [pageIndex, setPageIndex] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [meta, setMeta] = useState({ totalPages: 1, totalCount: 0 });

  const [formData, setFormData] = useState(emptyForm);
  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [deletingId, setDeletingId] = useState(null);
  const [detailOpen, setDetailOpen] = useState(false);
  const [detailVoucher, setDetailVoucher] = useState(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailOwner, setDetailOwner] = useState(null);

  const voucherIdOf = (item) => item?.voucherId || item?.id || item?.code;

  const loadVouchers = useCallback(async () => {
    try {
      setLoading(true);
      const response = await VoucherService.list(pageIndex, pageSize);
      const items = response?.items || response?.Items || [];
      const totalCount = response?.totalCount
        ?? response?.raw?.totalCount
        ?? items.length;
      const totalPages = response?.totalPages
        ?? response?.raw?.totalPages
        ?? Math.max(1, Math.ceil(totalCount / pageSize));

      setVouchers(items);
      setMeta({
        totalCount,
        totalPages,
        pageSize,
      });
    } catch (error) {
      console.error('Load vouchers error:', error);
      toast.error(
        error?.response?.data?.message
        || error?.message
        || 'Không thể tải danh sách voucher.',
      );
    } finally {
      setLoading(false);
    }
  }, [pageIndex, pageSize]);

  useEffect(() => {
    loadVouchers();
  }, [loadVouchers]);

  useEffect(() => {
    setPageIndex(1);
  }, [pageSize]);

  const openCreate = () => {
    setEditingId(null);
    setFormData({
      ...emptyForm,
      startDate: '',
      endDate: '',
    });
    setModalOpen(true);
  };

  const openEdit = (voucher) => {
    if (!voucher) return;
    setEditingId(voucherIdOf(voucher));
    setFormData({
      code: voucher.code || '',
      description: voucher.description || '',
      discountType: voucher.discountType || 'Percent',
      discountValue: voucher.discountValue ?? voucher.value ?? 0,
      minOrderAmount: voucher.minOrderAmount ?? '',
      maxDiscountAmount: voucher.maxDiscountAmount ?? '',
      startDate: toInputDateTime(voucher.startDate),
      endDate: toInputDateTime(voucher.endDate),
      usageLimit: voucher.usageLimit ?? 0,
      usedCount: voucher.usedCount ?? 0,
      isActive: voucher.isActive !== undefined ? voucher.isActive : true,
      createdById: voucher.createdById,
      isShared: voucher.isShared !== undefined ? voucher.isShared : true,
      singleUse: Boolean(voucher.singleUse),
      ownerUserId: voucher.ownerUserId || '',
      source: voucher.source || '',
      isAutoGenerated: voucher.isAutoGenerated,
    });
    setModalOpen(true);
  };

  const closeModal = () => {
    setModalOpen(false);
    setFormData(emptyForm);
    setEditingId(null);
  };

  const handleSave = async (e) => {
    e.preventDefault();
    const normalizeType = (raw) => {
      if (!raw) return 'Fixed';
      const lower = raw.toString().toLowerCase();
      if (lower.startsWith('f')) return 'Fixed';
      if (lower.startsWith('p')) return 'Percent';
      return raw;
    };

    const typeNormalized = normalizeType(formData.discountType);
    const parseDateInput = (value) => {
      if (!value) return null;
      const d = new Date(value);
      return Number.isNaN(d.getTime()) ? null : d;
    };

    if (!formData.code?.trim() || formData.code.trim().length < 4 || formData.code.trim().length > 20) {
      toast.error('Mã voucher phải từ 4–20 ký tự');
      return;
    }
    if (formData.description && formData.description.length > 200) {
      toast.error('Mô tả không được vượt quá 200 ký tự');
      return;
    }
    if (!typeNormalized) {
      toast.error('Loại giảm giá không được để trống');
      return;
    }
    const discountValue = numberOrZero(formData.discountValue);
    if (discountValue <= 0) {
      toast.error('Giá trị giảm giá phải lớn hơn 0');
      return;
    }
    const minOrderAmount = formData.minOrderAmount === '' || formData.minOrderAmount === null
      ? null
      : numberOrZero(formData.minOrderAmount);
    if (minOrderAmount !== null && minOrderAmount < 0) {
      toast.error('Giá trị đơn hàng tối thiểu không hợp lệ');
      return;
    }
    const maxDiscountAmount = typeNormalized === 'Percent'
      ? (formData.maxDiscountAmount === '' || formData.maxDiscountAmount === null
        ? null
        : numberOrZero(formData.maxDiscountAmount))
      : null;
    if (typeNormalized === 'Percent' && maxDiscountAmount !== null && maxDiscountAmount < 0) {
      toast.error('Giá trị giảm tối đa không hợp lệ');
      return;
    }
    const startDateObj = parseDateInput(formData.startDate);
    if (!startDateObj) {
      toast.error('Ngày bắt đầu không hợp lệ');
      return;
    }
    const endDateObj = parseDateInput(formData.endDate);
    if (!endDateObj) {
      toast.error('Ngày kết thúc không hợp lệ');
      return;
    }
    if (endDateObj <= startDateObj) {
      toast.error('Ngày kết thúc phải sau ngày bắt đầu');
      return;
    }
    const usageLimit = numberOrZero(formData.usageLimit);
    if (usageLimit <= 0) {
      toast.error('Giới hạn sử dụng phải lớn hơn 0');
      return;
    }
    if (formData.singleUse && !formData.ownerUserId?.trim()) {
      toast.error('Vui lòng nhập người được sử dụng cho voucher một lần');
      return;
    }

    const payload = {
      code: formData.code.trim(),
      description: formData.description?.trim() || '',
      discountType: typeNormalized,
      discountValue,
      minOrderAmount,
      maxDiscountAmount,
      usageLimit,
      usedCount: editingId ? formData.usedCount ?? 0 : 0,
      startDate: startDateObj.toISOString(),
      endDate: endDateObj.toISOString(),
      isActive: Boolean(formData.isActive),
      isShared: Boolean(formData.singleUse ? false : formData.isShared),
      singleUse: Boolean(formData.singleUse),
      ownerUserId: formData.singleUse ? formData.ownerUserId.trim() : null,
      source: formData.source?.trim() || null,
    };

    try {
      if (editingId) {
        await VoucherService.update(editingId, payload);
        toast.success('Đã cập nhật voucher');
      } else {
        await VoucherService.create(payload);
        toast.success('Đã tạo voucher mới');
      }
      closeModal();
      await loadVouchers();
    } catch (error) {
      console.error('Save voucher error:', error);
      toast.error(
        error?.response?.data?.message
        || error?.message
        || 'Không thể lưu voucher.',
      );
    }
  };

  const handleDelete = async (voucher) => {
    const id = voucherIdOf(voucher);
    if (!id) return;
    setDeletingId(id);
    try {
      await VoucherService.remove(id);
      toast.success('Đã xóa voucher');
      await loadVouchers();
    } catch (error) {
      console.error('Delete voucher error:', error);
      toast.error(
        error?.response?.data?.message
        || error?.message
        || 'Không thể xóa voucher.',
      );
    } finally {
      setDeletingId(null);
    }
  };

  const handleToggle = async (voucher) => {
    const id = voucherIdOf(voucher);
    if (!id) return;
    const payload = {
      ...voucher,
      isActive: !voucher.isActive,
    };
    try {
      await VoucherService.update(id, payload);
      toast.success(payload.isActive ? 'Đã kích hoạt voucher' : 'Đã vô hiệu hóa voucher');
      await loadVouchers();
    } catch (error) {
      console.error('Toggle voucher error:', error);
      toast.error(
        error?.response?.data?.message
        || error?.message
        || 'Không thể cập nhật trạng thái voucher.',
      );
    }
  };

  const displayedVouchers = useMemo(() => vouchers, [vouchers]);

  const scopeBadges = (voucher) => {
    const badges = [];
    badges.push(voucher.isAutoGenerated ? 'Tự động' : 'Admin');
    badges.push(voucher.isShared ? 'Dùng chung' : 'Giới hạn');
    if (voucher.singleUse) {
      badges.push('1 người');
    }
    return badges;
  };

  const openDetail = async (voucher) => {
    const id = voucherIdOf(voucher);
    if (!id) return;
    setDetailOpen(true);
    setDetailLoading(true);
    setDetailOwner(null);
    try {
      const data = await VoucherService.getById(id);
      setDetailVoucher(data);
      if (data?.ownerUserId) {
        try {
          const owner = await UserService.getById(data.ownerUserId);
          setDetailOwner(owner);
        } catch (error) {
          console.error('Fetch voucher owner error:', error);
          setDetailOwner(null);
        }
      }
    } catch (error) {
      console.error('Load voucher detail error:', error);
      toast.error(
        error?.response?.data?.message
        || error?.message
        || 'Không thể tải chi tiết voucher.',
      );
      setDetailVoucher(null);
    } finally {
      setDetailLoading(false);
    }
  };

  const closeDetail = () => {
    setDetailOpen(false);
    setDetailVoucher(null);
    setDetailOwner(null);
  };

  const getOwnerDisplay = () => {
    if (!detailVoucher?.ownerUserId) return '--';
    if (!detailOwner) return detailVoucher.ownerUserId;
    return (
      detailOwner.displayName
      || detailOwner.fullName
      || detailOwner.name
      || `${detailVoucher.ownerUserId}`
    );
  };

  return (
    <div className="bg-white rounded-xl shadow-md p-6">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-6">
        <div>
          <h2 className="text-xl font-bold text-gray-800 font-alata">Quản lý Voucher</h2>
          <p className="text-sm text-gray-600 mt-1">Tổng {meta.totalCount || displayedVouchers.length} voucher</p>
        </div>
        <div className="flex gap-3">
          <button
            type="button"
            onClick={loadVouchers}
            className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg flex items-center gap-2 hover:bg-gray-200 transition-colors"
          >
            <FaSync />
            Làm mới
          </button>
          <button
            type="button"
            onClick={openCreate}
            className="px-4 py-2 bg-primary text-white rounded-lg flex items-center gap-2 hover:bg-red-700 transition-colors"
          >
            <FaPlus />
            Thêm voucher
          </button>
        </div>
      </div>

      <div className="flex items-center gap-3 mb-4">
        <label className="text-sm text-gray-600">Số dòng:</label>
        <select
          value={pageSize}
          onChange={(e) => setPageSize(Number(e.target.value))}
          className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
        >
          {PAGE_SIZE_OPTIONS.map((size) => (
            <option key={size} value={size}>
              {size}
            </option>
          ))}
        </select>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full border-collapse">
          <thead>
            <tr className="bg-gray-50 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
              <th className="py-3 px-4">Mã & mô tả</th>
              <th className="py-3 px-4">Loại</th>
              <th className="py-3 px-4">Giá trị</th>
              <th className="py-3 px-4">Điều kiện</th>
              <th className="py-3 px-4">Hiệu lực</th>
              <th className="py-3 px-4">Sử dụng</th>
              <th className="py-3 px-4">Phạm vi</th>
              <th className="py-3 px-4">Trạng thái</th>
              <th className="py-3 px-4 text-center">Thao tác</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={10} className="py-6 text-center text-gray-500">
                  Đang tải dữ liệu...
                </td>
              </tr>
            ) : displayedVouchers.length === 0 ? (
              <tr>
                <td colSpan={10} className="py-6 text-center text-gray-500">
                  Chưa có voucher nào.
                </td>
              </tr>
            ) : (
              displayedVouchers.map((voucher) => {
                const id = voucherIdOf(voucher);
                const typeLower = (voucher.discountType || '').toLowerCase();
                const isPercent = typeLower === 'percent' || typeLower === 'percentage';
                return (
                  <tr key={id || voucher.code} className="border-b hover:bg-gray-50 text-sm">
                    <td className="py-3 px-4">
                      <div className="font-semibold text-gray-800">{voucher.code || id}</div>
                      <div className="text-xs text-gray-500">{voucher.description || '--'}</div>
                      {voucher.source && (
                        <div className="text-xs text-gray-400 mt-1">Nguồn: {voucher.source}</div>
                      )}
                    </td>
                    <td className="py-3 px-4 text-gray-700 capitalize">
                      <div>{voucher.discountType || '--'}</div>
                      <div className="text-xs text-gray-500">
                        {voucher.isAutoGenerated ? 'Hệ thống' : 'Admin'}
                      </div>
                    </td>
                    <td className="py-3 px-4 text-gray-700">
                      <div>
                        {isPercent ? `${numberOrZero(voucher.discountValue)}%` : formatCurrency(voucher.discountValue)}
                      </div>
                      {isPercent && voucher.maxDiscountAmount !== null && voucher.maxDiscountAmount !== undefined && (
                        <div className="text-xs text-gray-500">
                          Tối đa: {formatCurrency(voucher.maxDiscountAmount)}
                        </div>
                      )}
                    </td>
                    <td className="py-3 px-4 text-gray-700">
                      <div>Đơn tối thiểu: {formatAmountOrDash(voucher.minOrderAmount)}</div>
                      {voucher.ownerUserId && (
                        <div className="text-xs text-gray-500">Owner: {voucher.ownerUserId}</div>
                      )}
                    </td>
                    <td className="py-3 px-4 text-gray-700">
                      <div>Bắt đầu: {formatDateTime(voucher.startDate)}</div>
                      <div className="text-xs text-gray-500">Kết thúc: {formatDateTime(voucher.endDate)}</div>
                    </td>
                    <td className="py-3 px-4 text-gray-700">
                      <div>Giới hạn: {voucher.usageLimit ?? '--'}</div>
                      <div className="text-xs text-gray-500">Đã dùng: {voucher.usedCount ?? 0}</div>
                    </td>
                    <td className="py-3 px-4 text-gray-700">
                      <div className="flex flex-wrap gap-1">
                        {scopeBadges(voucher).map((badge) => (
                          <span
                            key={`${id}-${badge}`}
                            className="px-2 py-1 rounded-full bg-gray-100 text-gray-700 text-xs font-medium"
                          >
                            {badge}
                          </span>
                        ))}
                      </div>
                      {!voucher.isShared && !voucher.singleUse && (
                        <div className="text-xs text-gray-500 mt-1">Voucher riêng</div>
                      )}
                      {voucher.singleUse && (
                        <div className="text-xs text-gray-500 mt-1">
                          {voucher.ownerUserId ? `Chỉ định: ${voucher.ownerUserId}` : '1 người dùng'}
                        </div>
                      )}
                    </td>
                    <td className="py-3 px-4">
                      <span
                        className={`px-3 py-1 rounded-full text-xs font-semibold ${
                          voucher.isActive ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                        }`}
                      >
                        {voucher.isActive ? 'Đang hiệu lực' : 'Đã tắt'}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex flex-wrap gap-2 justify-center">
                        <button
                          type="button"
                          onClick={() => openDetail(voucher)}
                          className="px-3 py-2 rounded-lg text-indigo-600 border border-indigo-200 hover:bg-indigo-50 flex items-center gap-1 text-xs"
                        >
                          <FaEye /> Chi tiết
                        </button>
                        <button
                          type="button"
                          onClick={() => handleToggle(voucher)}
                          className={`px-3 py-2 rounded-lg text-white text-xs ${
                            voucher.isActive ? 'bg-red-600 hover:bg-red-700' : 'bg-green-600 hover:bg-green-700'
                          }`}
                        >
                          {voucher.isActive ? 'Vô hiệu hóa' : 'Kích hoạt'}
                        </button>
                        <button
                          type="button"
                          onClick={() => openEdit(voucher)}
                          className="px-3 py-2 rounded-lg text-blue-600 border border-blue-200 hover:bg-blue-50 flex items-center gap-1 text-xs"
                        >
                          <FaEdit /> Sửa
                        </button>
                        <button
                          type="button"
                          disabled={deletingId === id}
                          onClick={() => handleDelete(voucher)}
                          className="px-3 py-2 rounded-lg text-red-600 border border-red-200 hover:bg-red-50 flex items-center gap-1 text-xs disabled:opacity-60"
                        >
                          <FaTrash /> Xóa
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

      {!loading && meta.totalPages > 1 && (
        <Pagination
          totalPages={meta.totalPages}
          pageIndex={pageIndex}
          setPageIndex={setPageIndex}
        />
      )}

      {modalOpen && (
        <div className="fixed inset-0 bg-black/30 flex items-center justify-center z-40">
          <div className="bg-white rounded-lg shadow-xl w-full max-w-3xl p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-800">{editingId ? 'Cập nhật voucher' : 'Thêm voucher mới'}</h3>
              <button
                type="button"
                onClick={closeModal}
                className="text-gray-500 hover:text-gray-700"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleSave} className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Mã voucher</label>
                <input
                  required
                  value={formData.code}
                  onChange={(e) => setFormData({ ...formData, code: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Loại giảm</label>
                <select
                  value={formData.discountType}
                  onChange={(e) => setFormData({ ...formData, discountType: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                >
                  <option value="Fixed">Fixed</option>
                  <option value="Percent">Percent</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Giá trị giảm</label>
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  value={formData.discountValue}
                  onChange={(e) => setFormData({ ...formData, discountValue: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Mô tả</label>
                <input
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Đơn tối thiểu</label>
                <input
                  type="number"
                  min="0"
                  value={formData.minOrderAmount}
                  onChange={(e) => setFormData({ ...formData, minOrderAmount: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              {['percentage', 'percent'].includes((formData?.discountType || '').toLowerCase()) && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Giảm tối đa</label>
                  <input
                    type="number"
                    min="0"
                    value={formData.maxDiscountAmount}
                    onChange={(e) => setFormData({ ...formData, maxDiscountAmount: e.target.value })}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                  />
                </div>
              )}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Ngày bắt đầu</label>
                <input
                  type="datetime-local"
                  value={formData.startDate}
                  onChange={(e) => setFormData({ ...formData, startDate: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Ngày kết thúc</label>
                <input
                  type="datetime-local"
                  value={formData.endDate}
                  onChange={(e) => setFormData({ ...formData, endDate: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Giới hạn lượt dùng</label>
                <input
                  type="number"
                  min="0"
                  value={formData.usageLimit}
                  onChange={(e) => setFormData({ ...formData, usageLimit: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              <div className="flex items-center gap-2 mt-2">
                <input
                  id="isShared"
                  type="checkbox"
                  checked={formData.isShared && !formData.singleUse}
                  disabled={formData.singleUse}
                  onChange={(e) => setFormData({ ...formData, isShared: e.target.checked })}
                  className="w-4 h-4 text-primary focus:ring-primary border-gray-300 rounded disabled:opacity-60"
                />
                <label htmlFor="isShared" className="text-sm text-gray-700">Voucher dùng chung</label>
              </div>
              <div className="flex items-center gap-2">
                <input
                  id="singleUse"
                  type="checkbox"
                  checked={formData.singleUse}
                  onChange={(e) => setFormData({
                    ...formData,
                    singleUse: e.target.checked,
                    isShared: e.target.checked ? false : formData.isShared,
                  })}
                  className="w-4 h-4 text-primary focus:ring-primary border-gray-300 rounded"
                />
                <label htmlFor="singleUse" className="text-sm text-gray-700">Voucher cá nhân (1 người dùng)</label>
              </div>
              {formData.singleUse && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Owner userId</label>
                  <input
                    value={formData.ownerUserId}
                    onChange={(e) => setFormData({ ...formData, ownerUserId: e.target.value })}
                    placeholder="Nhập userId được phép sử dụng"
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                  />
                </div>
              )}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Nguồn (source)</label>
                <input
                  value={formData.source}
                  onChange={(e) => setFormData({ ...formData, source: e.target.value })}
                  placeholder="VD: FESTIVAL:SPRING"
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              {/* usedCount hidden on create, kept in state for update consistency */}
              <div className="flex items-center gap-2">
                <input
                  id="isActive"
                  type="checkbox"
                  checked={formData.isActive}
                  onChange={(e) => setFormData({ ...formData, isActive: e.target.checked })}
                  className="w-4 h-4 text-primary focus:ring-primary border-gray-300 rounded"
                />
                <label htmlFor="isActive" className="text-sm text-gray-700">Kích hoạt</label>
              </div>

              <div className="md:col-span-2 flex justify-end gap-3 mt-4">
                <button
                  type="button"
                  onClick={closeModal}
                  className="px-4 py-2 rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50"
                >
                  Hủy
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-lg bg-primary text-white hover:bg-red-700"
                >
                  {editingId ? 'Cập nhật' : 'Tạo mới'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {detailOpen && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-40 px-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-2xl">
            <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
              <div>
                <h3 className="text-lg font-semibold text-gray-800">Chi tiết voucher</h3>
                {detailVoucher?.code && (
                  <p className="text-sm text-gray-500">Mã: {detailVoucher.code}</p>
                )}
              </div>
              <button
                type="button"
                onClick={closeDetail}
                className="text-gray-500 hover:text-gray-700"
              >
                ×
              </button>
            </div>
            <div className="px-6 py-5 max-h-[70vh] overflow-y-auto text-sm text-gray-700">
              {detailLoading ? (
                <div className="flex items-center justify-center py-8 gap-2 text-gray-600">
                  <FaSpinner className="animate-spin" />
                  <span>Đang tải chi tiết...</span>
                </div>
              ) : !detailVoucher ? (
                <p className="text-center text-gray-500 py-6">Không tìm thấy dữ liệu</p>
              ) : (
                <div className="space-y-4">
                  <div>
                    <p className="text-xs uppercase text-gray-500">Mô tả</p>
                    <p className="font-semibold text-gray-900">{detailVoucher.description || '--'}</p>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <p className="text-xs uppercase text-gray-500">Loại</p>
                      <p className="font-semibold">{detailVoucher.discountType}</p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Giá trị</p>
                      <p className="font-semibold">
                        {(detailVoucher.discountType || '').toLowerCase() === 'percent'
                          ? `${numberOrZero(detailVoucher.discountValue)}%`
                          : formatCurrency(detailVoucher.discountValue)}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Đơn tối thiểu</p>
                      <p className="font-semibold">{formatAmountOrDash(detailVoucher.minOrderAmount)}</p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Giảm tối đa</p>
                      <p className="font-semibold">{formatAmountOrDash(detailVoucher.maxDiscountAmount)}</p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Bắt đầu</p>
                      <p className="font-semibold">{formatDateTime(detailVoucher.startDate)}</p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Kết thúc</p>
                      <p className="font-semibold">{formatDateTime(detailVoucher.endDate)}</p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Giới hạn / Đã dùng</p>
                      <p className="font-semibold">
                        {detailVoucher.usageLimit ?? '--'} / {detailVoucher.usedCount ?? 0}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Trạng thái</p>
                      <span
                        className={`inline-block px-3 py-1 rounded-full text-xs font-semibold ${
                          detailVoucher.isActive ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                        }`}
                      >
                        {detailVoucher.isActive ? 'Đang hiệu lực' : 'Đã tắt'}
                      </span>
                    </div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <p className="text-xs uppercase text-gray-500">Phạm vi</p>
                      <p className="font-semibold">
                        {detailVoucher.isShared ? 'Voucher chung' : 'Voucher riêng'}
                        {detailVoucher.singleUse ? ' • Dùng 1 lần' : ''}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Người sở hữu</p>
                      <p className="font-semibold">
                        {getOwnerDisplay()}
                        {detailOwner?.email && (
                          <span className="block text-xs text-gray-500">{detailOwner.email}</span>
                        )}
                        {detailOwner && (
                          <span className="block text-xs text-gray-400">ID: {detailVoucher.ownerUserId}</span>
                        )}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Nguồn / Tự động</p>
                      <p className="font-semibold">
                        {(detailVoucher.isAutoGenerated ? 'Hệ thống' : 'Admin')}
                        {detailVoucher.source ? ` • ${detailVoucher.source}` : ''}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Người tạo</p>
                      <p className="font-semibold">{detailVoucher.createdById || '--'}</p>
                    </div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <p className="text-xs uppercase text-gray-500">Ngày tạo</p>
                      <p className="font-semibold">{formatDateTime(detailVoucher.createdDate)}</p>
                    </div>
                    <div>
                      <p className="text-xs uppercase text-gray-500">Cập nhật gần nhất</p>
                      <p className="font-semibold">{formatDateTime(detailVoucher.updatedDate)}</p>
                    </div>
                  </div>
                </div>
              )}
            </div>
            <div className="px-6 py-4 border-t border-gray-200 flex justify-end">
              <button
                type="button"
                onClick={closeDetail}
                className="px-4 py-2 rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50"
              >
                Đóng
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default VoucherManagement;
