using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_SEP490.Migrations
{
    /// <inheritdoc />
    public partial class AddVoucherScopes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "AssignedAt",
                table: "Vouchers",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Vouchers",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsShared",
                table: "Vouchers",
                type: "boolean",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "LastReminderAt",
                table: "Vouchers",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "OwnerUserId",
                table: "Vouchers",
                type: "character varying(450)",
                maxLength: 450,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "SingleUse",
                table: "Vouchers",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "Source",
                table: "Vouchers",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Vouchers_Code",
                table: "Vouchers",
                column: "Code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Vouchers_OwnerUserId",
                table: "Vouchers",
                column: "OwnerUserId");

            migrationBuilder.CreateIndex(
                name: "IX_Vouchers_Source",
                table: "Vouchers",
                column: "Source");

            migrationBuilder.AddForeignKey(
                name: "FK_Vouchers_Users_OwnerUserId",
                table: "Vouchers",
                column: "OwnerUserId",
                principalTable: "Users",
                principalColumn: "UserID",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Vouchers_Users_OwnerUserId",
                table: "Vouchers");

            migrationBuilder.DropIndex(
                name: "IX_Vouchers_Code",
                table: "Vouchers");

            migrationBuilder.DropIndex(
                name: "IX_Vouchers_OwnerUserId",
                table: "Vouchers");

            migrationBuilder.DropIndex(
                name: "IX_Vouchers_Source",
                table: "Vouchers");

            migrationBuilder.DropColumn(
                name: "AssignedAt",
                table: "Vouchers");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Vouchers");

            migrationBuilder.DropColumn(
                name: "IsShared",
                table: "Vouchers");

            migrationBuilder.DropColumn(
                name: "LastReminderAt",
                table: "Vouchers");

            migrationBuilder.DropColumn(
                name: "OwnerUserId",
                table: "Vouchers");

            migrationBuilder.DropColumn(
                name: "SingleUse",
                table: "Vouchers");

            migrationBuilder.DropColumn(
                name: "Source",
                table: "Vouchers");
        }
    }
}
